function out = alm_rcg_isac(data, para, x_init)
% ALM_RCG_ISAC  ALM-RCG-based ISAC waveform design.
%
% This function implements the low-complexity ALM-RCG method in:
%   P. Li et al., IEEE Trans. Veh. Technol., 2025.
%
% Inputs:
%   data   : Problem data generated by BUILD_DEMO_INSTANCE.
%            It contains the AF matrix, illumination matrix, and
%            communication-constraint matrices.
%   para   : Parameter struct generated by PAPER_PARAMS.
%   x_init : Initial waveform vector in the frequency domain.
%
% Output:
%   out    : Struct containing the designed waveform, final metrics,
%            dual variables, and iteration history.

% Check Manopt dependency.
if exist('complexcirclefactory', 'file') ~= 2 || exist('conjugategradient', 'file') ~= 2
    error(['Manopt is not on MATLAB path. Please add Manopt first, e.g.\n' ...
        'addpath(genpath(''/path/to/manopt''));']);
end

% Prepare normalized quantities used in the ALM objective
aux = prepare_alm_rcg_terms(data, para);

% Work in the time domain, where the constant-modulus constraint is simple
x_time = data.FeH * x_init;

% Initialize ALM dual variables and penalty parameter
omega = 0;
kappa = zeros(size(data.gammaVec));
rho   = para.alm_rho0;
prev_feas = inf;

% Initial performance.
[isl_val, islr_val, ml_val] = compute_islr(x_init, data);
history = struct();
history.isl             = isl_val;
history.islr            = islr_val;
history.ml              = ml_val;
history.isl_db          = 10 * log10(max(isl_val, eps));
history.islr_db         = 10 * log10(max(islr_val, eps));
history.ml_db           = 10 * log10(max(ml_val, eps));
history.delta_out       = [];
history.inner_iters     = [];
history.inner_cost      = [];
history.inner_gradnorm  = [];
history.illum_violation = [];
history.comm_violation  = [];

if isfield(para, 'show_progress_alm') && para.show_progress_alm
    fprintf('  [ALM-RCG] start: ISL = %.4f dB, ML = %.4f dB, ISLR = %.4f dB\n', ...
        history.isl_db(end), history.ml_db(end), history.islr_db(end));
end

for outer_iter = 1:para.alm_outer_max
    % Normalize the ISL term using the current point
    u_ref = exp(1j * angle(x_time));
    r_ref = data.AF * u_ref;
    p_ref = abs(r_ref).^2;
    aux.isl_scale = max(para.amp^4 * real(p_ref' * (aux.W * p_ref)), 1);

    % Inner RCG step on the complex circle manifold
    [x_time_new, xcost, info] = alm_rcg_inner(x_time, data, para, aux, rho, omega, kappa);
    % Constraint residuals in the original scale
    illum_res = real(x_time_new' * data.Ahat * x_time_new) - para.Pbar0;
    comm_res  = data.gammaVec - real(data.Hhat * x_time_new);
    % Scaled residuals used in the ALM updates
    illum_res_s = illum_res / (para.amp^2 * aux.ill_scale);
    comm_res_s  = comm_res  / (para.amp   * aux.comm_scale);    
    % Dual-variable updates, corresponding to the ALM formulation
    omega = max(0, omega + rho * illum_res_s);
    kappa = max(0, kappa + rho * comm_res_s);
    % Increase rho if feasibility is not improving sufficiently
    feas = max([max(comm_res_s), max(illum_res_s, 0)]);
    if outer_iter > 1 && feas > 0.9 * prev_feas
        rho = min(1.3 * rho, para.alm_rho_max);
    end
    prev_feas = feas;
    % Evaluate the updated waveform in the frequency domain
    x_freq_new = data.Fe * x_time_new;
    [isl_val, islr_val, ml_val] = compute_islr(x_freq_new, data);

    delta_out = norm(x_time_new - x_time);
    history.isl(end+1, 1)             = isl_val;
    history.islr(end+1, 1)            = islr_val;
    history.ml(end+1, 1)              = ml_val;
    history.isl_db(end+1, 1)          = 10 * log10(max(isl_val, eps));
    history.islr_db(end+1, 1)         = 10 * log10(max(islr_val, eps));
    history.ml_db(end+1, 1)           = 10 * log10(max(ml_val, eps));
    history.delta_out(end+1, 1)       = delta_out;
    history.inner_cost(end+1, 1)      = xcost;
    history.illum_violation(end+1, 1) = max(illum_res, 0);
    history.comm_violation(end+1, 1)  = max(comm_res);

    if ~isempty(info) && isstruct(info)
        if isfield(info, 'iter')
            history.inner_iters(end+1, 1) = info(end).iter;
        else
            history.inner_iters(end+1, 1) = numel(info);
        end
        if isfield(info, 'gradnorm')
            history.inner_gradnorm(end+1, 1) = info(end).gradnorm;
        else
            history.inner_gradnorm(end+1, 1) = NaN;
        end
    else
        history.inner_iters(end+1, 1)    = NaN;
        history.inner_gradnorm(end+1, 1) = NaN;
    end

    if isfield(para, 'show_progress_alm') && para.show_progress_alm
        fprintf(['  [outer %3d] delta = %.3e | ISL = %.4f dB | ML = %.4f dB | ISLR = %.4f dB | ' ...
            'illum viol = %.3e | comm viol = %.3e\n'], ...
            outer_iter, delta_out, history.isl_db(end), history.ml_db(end), history.islr_db(end), ...
            history.illum_violation(end), history.comm_violation(end));
    end
    x_time = x_time_new;
    if delta_out <= para.delta_th &&  history.comm_violation(end) <= 1e-8 && ...
            history.illum_violation(end) <= 1e-8
        break;
    end
end

out = struct();
out.x                = data.Fe * x_time;
out.x_time           = x_time;
out.isl              = history.isl(end);
out.islr             = history.islr(end);
out.ml               = history.ml(end);
out.isl_db           = history.isl_db(end);
out.islr_db          = history.islr_db(end);
out.ml_db            = history.ml_db(end);
out.omega            = omega;
out.kappa            = kappa;
out.rho              = rho;
out.history          = history;
out.outer_iters      = outer_iter;
out.illum_violation  = history.illum_violation(end);
out.comm_violation   = history.comm_violation(end);
end


function aux = prepare_alm_rcg_terms(data, para)
% PREPARE_ALM_RCG_TERMS  Precompute normalized quantities for ALM-RCG
aux = struct();
% Diagonal matrix/vector used in the ISL expression
aux.W = reshape(full(data.bdiag), para.M, para.M);
aux.W = real(0.5 * (aux.W + aux.W.'));
% Normalized thresholds used in the augmented Lagrangian
aux.Pbar_nor   = para.Pbar0 / (para.amp^2);
aux.gamma_nor  = data.gammaVec / para.amp;
aux.comm_scale = max(aux.gamma_nor);
aux.ill_scale = aux.Pbar_nor;
end


function [x_time_opt, xcost, info] = alm_rcg_inner(x_time0, data, para, aux, rho, omega, kappa)
% ALM_RCG_INNER  Solve one ALM subproblem on the complex circle manifold
manifold = complexcirclefactory(para.Ntot);
problem.M = manifold;
% Unit-modulus manifold variable; actual waveform is para.amp * u
u0 = exp(1j * angle(x_time0));
% ALM objective in the TVT paper, Eq. (18), using cost in Eq. (9)
problem.cost = @(u) alm_rcg_cost(u, data, para, aux, rho, omega, kappa);
% Euclidean gradient corresponds to the closed-form expression in Eq. (10),
% then projected to the Riemannian gradient by Manopt
problem.grad = @(u) problem.M.egrad2rgrad(u, ...
    alm_rcg_egrad(u, data, para, aux, rho, omega, kappa));

options = struct();
options.maxiter = para.rcg_maxiter;
options.tolgradnorm = para.rcg_tolgradnorm;
options.minstepsize = para.rcg_minstepsize;
options.verbosity = para.rcg_verbosity;
% checkgradient(problem)

[u_opt, xcost, info] = conjugategradient(problem, u0, options);
% Recover the constant-modulus time-domain waveform
x_time_opt = para.amp * exp(1j * angle(u_opt));
end


function f = alm_rcg_cost(u, data, para, aux, rho, omega, kappa)
% ALM_RCG_COST  Augmented-Lagrangian cost on the unit-modulus manifold
% ISL term
r = data.AF * u;
p = abs(r).^2;
f_isl = para.amp^4 * real(p' * (aux.W * p)) / aux.isl_scale;

% Illumination constraint penalty
g_ill = (real(u' * (data.Ahat * u)) - aux.Pbar_nor) / aux.ill_scale;
t_ill = g_ill + omega / rho;
f_ill = 0.5 * rho * max(t_ill, 0)^2;

% Communication QoS penalty
g_comm = (aux.gamma_nor - real(data.Hhat * u)) / aux.comm_scale;
t_comm = g_comm + kappa / rho;
f_comm = 0.5 * rho * sum(max(t_comm, 0).^2);

f = real(f_isl + f_ill + f_comm);
end


function g = alm_rcg_egrad(u, data, para, aux, rho, omega, kappa)
% ALM_RCG_EGRAD  Euclidean gradient of the ALM objective
% This corresponds to the closed-form gradient expression in Eq. (10)
% of the TVT 2025 paper

% Gradient of the ISL term
r = data.AF * u;
p = abs(r).^2;
q = aux.W * p;
g_isl = (para.amp^4 / aux.isl_scale) * 4 * (data.AF' * (q .* r));

% Gradient of the illumination penalty
g_ill_raw = (real(u' * (data.Ahat * u)) - aux.Pbar_nor) / aux.ill_scale;
t_ill = g_ill_raw + omega / rho;
if t_ill > 0
    g_ill = 2 * (rho / aux.ill_scale) * t_ill * (data.Ahat * u);
else
    g_ill = zeros(para.Ntot, 1);
end

% Gradient of the communication QoS penalty
tmp = (real(data.Hhat * u) - aux.gamma_nor) / aux.comm_scale - kappa / rho;
g_comm = (rho / aux.comm_scale) * (data.Hhat' * min(tmp, 0));

g = g_isl + g_ill + g_comm;
end