function data = build_demo_instance(para)
% BUILD_DEMO_INSTANCE  Build one random simulation instance.
%
% Input:
%   para : Parameter struct generated by PAPER_PARAMS.
%
% Output:
%   data : Struct containing all matrices needed by the algorithms,
%          including the Fourier transform matrices, AF operator,
%          illumination constraint matrices, communication constraints,
%          and random communication channels.

% Target steering vector and rank-one transmit covariance along theta0
aT = exp(1j * 2 * pi * (0:para.Nt-1).' * para.dT * sin(para.theta0_rad) / para.lambda);
At = aT * aT';

% Nc-point normalized DFT matrix and the full transform matrix
Fnc = exp(-1j * 2 * pi / para.Nc * ((0:para.Nc-1).' * (0:para.Nc-1))) / sqrt(para.Nc);
Fe = kron(eye(para.Ns), kron(Fnc, eye(para.Nt)));
FeH = Fe';

% Ae maps x to the target-direction beamformed signal across all bins
Ae = kron(eye(para.M), aT);
AeH = Ae';
P = Ae * AeH;

% Illumination constraint matrix.
% This is related to the reformulation in the TWC paper, Eqs. (29), (30) and (35b)
Q0 = para.Nt * eye(para.Nt) - At;
Q0 = (Q0 + Q0') / 2;
[U, D] = eig(full(Q0));
d = max(real(diag(D)), 0);
L0 = diag(sqrt(d)) * U';
Ahat = kron(eye(para.Ns*para.Nc), Q0);

% Diagonal entries of B in the vectorized ISL formulation, Eq. (34)
bdiag = build_B_diag(para.Nc, para.Ns);
lambdaB = para.M - 1;

% Random M-PSK communication symbols
symbol_set = exp(1j * pi * (2 * (1:para.Mpsk) - 1) / para.Mpsk);
sym_idx = randi(para.Mpsk, [para.K, para.Nc, para.Ns]);
S = symbol_set(sym_idx);

% Random user channels and constructive-interference constraints
[Hf, user_dist] = generate_user_channels(para);
[Ccomm, gammaVec] = build_comm_constraints(S, Hf, para);

data = struct();
data.aT = aT;
data.At = At;
data.Fe = Fe;
data.FeH = FeH;
data.Ae = Ae;
data.AeH = AeH;
data.P = P;
data.Cill = kron(speye(para.M), sparse(L0));
data.Ahat = Ahat;
data.bdiag = bdiag;
data.lambdaB = lambdaB;
data.Ccomm = Ccomm;
data.gammaVec = gammaVec;
data.S = S;
data.Hf = Hf;
data.user_dist = user_dist;
data.AF = AeH * Fe;
data.Hhat = Ccomm * Fe;
end

function [Hf, user_dist] = generate_user_channels(para)
% GENERATE_USER_CHANNELS  Generate random frequency-selective user channels

Hf = zeros(para.Nt, para.Nc, para.K);
user_dist = zeros(para.K, 1);
for k = 1:para.K
    % Random user distance
    d = para.user_dist_min + (para.user_dist_max - para.user_dist_min) * rand();
    user_dist(k) = d;
    % Distance-based pathloss and small-scale fading
    pl = para.pathloss_zeta0 * (d / para.d0)^(-para.epsilon);
    Hf(:,:,k) = sqrt(pl) * (randn(para.Nt, para.Nc) + 1j * randn(para.Nt, para.Nc)) / sqrt(2);
end
end

function [Ccomm, gammaVec] = build_comm_constraints(S, Hf, para)
% BUILD_COMM_CONSTRAINTS  Build real-valued CI-based communication constraints.
%
% The resulting constraints are of the form
%   real(Ccomm * x) >= gammaVec.

Ncon = 2 * para.K * para.Nc * para.Ns;
NnzPerRow = para.Nt;
NnzTotal = Ncon * NnzPerRow;

rows = zeros(NnzTotal, 1);
cols = zeros(NnzTotal, 1);
vals = zeros(NnzTotal, 1);
gammaVec = zeros(Ncon, 1);

row_ptr = 0;
nnz_ptr = 0;
base_g = para.sigma_c * sqrt(para.Gamma_lin) * sin(para.phi);

for m = 1:para.Ns
    for n = 1:para.Nc
        blk0 = (m - 1) * para.Nc + (n - 1);
        x_idx = (blk0 * para.Nt + 1):((blk0 + 1) * para.Nt);

        for k = 1:para.K
            s_nmk = S(k, n, m);
            h_nk = Hf(:, n, k);
            
            % Two real half-space inequalities for CI-based M-PSK detection
            he1 = conj(s_nmk) * (sin(para.phi) - 1j * cos(para.phi)) * conj(h_nk);
            he2 = conj(s_nmk) * (sin(para.phi) + 1j * cos(para.phi)) * conj(h_nk);

            span = nnz_ptr + (1:para.Nt);

            row_ptr = row_ptr + 1;
            rows(span) = row_ptr;
            cols(span) = x_idx;
            vals(span) = he1;
            gammaVec(row_ptr) = base_g;
            nnz_ptr = nnz_ptr + para.Nt;

            span = nnz_ptr + (1:para.Nt);
            row_ptr = row_ptr + 1;
            rows(span) = row_ptr;
            cols(span) = x_idx;
            vals(span) = he2;
            gammaVec(row_ptr) = base_g;
            nnz_ptr = nnz_ptr + para.Nt;
        end
    end
end
Ccomm = sparse(rows, cols, vals, Ncon, para.Ntot);
end

function bdiag = build_B_diag(Nc, Ns)
% BUILD_B_DIAG  Build the diagonal entries of matrix B.
%
% This corresponds to the compact/vectorized ISL formulation in the
% TWC 2025 paper, especially Eq. (34).

M = Nc * Ns;
idx = (0:(M * M - 1)).';

n  = mod(idx, Nc);
mp = mod(floor(idx / Nc), Ns);
np = mod(floor(idx / (Ns * Nc)), Nc);
m  = mod(floor(idx / (Ns * Nc * Nc)), Ns);

is_mainlobe = (n == np) & (m == mp);
bdiag = -ones(M * M, 1);
bdiag(is_mainlobe) = M - 1;
end
