function out = combined_waveform_baseline(data, para)
% COMBINED_WAVEFORM_BASELINE  Combined communication-radar baseline [30]:
% X. Liu, T. Huang, N. Shlezinger, Y. Liu, J. Zhou, and Y. C. Eldar, "Joint 
% transmit beamforming for multiuser MIMO communications and MIMO
% radar," IEEE Trans. Signal Process., vol. 68, pp. 3929–3944, Jun. 2020.
%
% Inputs:
%   data : Struct generated by BUILD_DEMO_INSTANCE.
%   para : Parameter struct generated by PAPER_PARAMS.
%
% Output:
%   out  : Struct containing the baseline waveform and its metrics.

Nt = para.Nt;
Nc = para.Nc;
Ns = para.Ns;

% Equal power per subcarrier-symbol block
Psc = para.PT / (Nc * Ns);
% Communication symbols and radar reference waveform
s_comm = data.S;
s_radar = zc_beamformed(Nt, Nc, Ns, data.aT);
Hn = squeeze(data.Hf(:, 1, :));

[Wc, Wr, info] = design_combined_beamformer(Hn, para, Psc);
X = zeros(Nt, Nc, Ns);
for m = 1:Ns
    for n = 1:Nc
        X(:, n, m) = Wc * s_comm(:, n, m) + Wr * s_radar(:, n, m);
    end
end
x = X(:);
x = sqrt(para.PT / max(norm(x)^2, eps)) * x;
[isl_val, islr_val, ml_val] = compute_islr(x, data);

out = struct();
out.x = x;
out.x_time = data.FeH * x;
out.isl = isl_val;
out.islr = islr_val;
out.ml = ml_val;
out.isl_db = 10 * log10(max(isl_val, eps));
out.islr_db = 10 * log10(max(islr_val, eps));
out.ml_db = 10 * log10(max(ml_val, eps));
out.Wc = Wc;
out.Wr = Wr;
out.info = info;
end

function [Wc, Wr, info] = design_combined_beamformer(Hn, para, Psc)
% DESIGN_COMBINED_BEAMFORMER  Beamformer design for the combined baseline.
%
% Inputs:
%   Hn  : Channel matrix at one subcarrier, size Nt x K.
%   para: Parameter struct.
%   Psc : Power per subcarrier-symbol block.
%
% Outputs:
%   Wc  : Communication beamformer.
%   Wr  : Radar beamformer.
%   info: CVX status information.

Nt = para.Nt;
K  = para.K;
wc = para.wc;

sigma2 = para.sigma_c2;
gamma  = para.Gamma_lin;

% Desired radar beampattern on an angular grid
theta_grid = -90:1:90;
beam_width = 10;
p_theta = zeros(size(theta_grid));
beam_centers = para.theta0_deg(:).';
for ii = 1:numel(beam_centers)
    idx = theta_grid >= (beam_centers(ii) - beam_width/2) & ...
        theta_grid <= (beam_centers(ii) + beam_width/2);
    p_theta(idx) = 1;
end

cvx_begin quiet
variable alp nonnegative
variable R(Nt, Nt) complex hermitian semidefinite
variable RR(Nt, Nt, K) complex hermitian semidefinite
variable t
expression fun
fun = 0;
% Pattern fitting term
for i = 1:numel(theta_grid)
    a = exp(-1j * pi * (0:Nt-1).' * sin(deg2rad(theta_grid(i))));
    fun = fun + square_pos(abs(alp * p_theta(i) - a' * R * a)) / numel(theta_grid);
end
% Cross-beam suppression term between beam centers
for i = 1:numel(beam_centers)-1
    ai = exp(-1j * pi * (0:Nt-1).' * sin(deg2rad(beam_centers(i))));
    for j = i+1:numel(beam_centers)
        aj = exp(-1j * pi * (0:Nt-1).' * sin(deg2rad(beam_centers(j))));
        fun = fun + wc * 2 / (numel(beam_centers) * (numel(beam_centers)-1)) ...
            * square_pos(abs(ai' * R * aj));
    end
end

minimize(t)
subject to
t >= fun;
% Decompose the total covariance into communication + radar parts
R - sum(RR, 3) == hermitian_semidefinite(Nt);

% Equal per-antenna power on each (subcarrier, symbol)
for ii = 1:Nt
    R(ii, ii) == Psc / Nt;
end

% Communication SINR constraints
for k = 1:K
    hk = Hn(:, k);
    real((1 + 1/gamma) * hk' * RR(:, :, k) * hk) >= real(hk' * R * hk) + sigma2;
end
cvx_end

info = struct();
info.cvx_status = cvx_status;
info.cvx_optval = cvx_optval;

if ~(contains(cvx_status, 'Solved') || contains(cvx_status, 'Inaccurate'))
    error('design_combined_beamformer failed, CVX status = %s', cvx_status);
end

% Recover communication beamformers from RR
Wc = zeros(Nt, K);
Rr = R;
for k = 1:K
    hk = Hn(:, k);
    denom = real(hk' * RR(:, :, k) * hk);
    denom = max(denom, eps);
    wk = RR(:, :, k) * hk / sqrt(denom);
    Wc(:, k) = wk;
    Rr = Rr - wk * wk';
end

% Recover a radar beamformer factor from the remaining covariance
Rr = (Rr + Rr') / 2;
[V, D] = eig(full(Rr));
d = max(real(diag(D)), 0);
Wr = V * diag(sqrt(d));
end