function [x0, info] = comm_wave(data, para)
% COMM_WAVE  Communication-only waveform initialization in the TWC paper eq. (59).
%
% Inputs:
%   data : Struct generated by BUILD_DEMO_INSTANCE.
%   para : Parameter struct generated by PAPER_PARAMS.
%
% Outputs:
%   x0   : Communication-only waveform in the frequency domain.
%   info : CVX solver information.

if ~para.use_cvx
    error('This reproduction currently expects CVX for the initialization step.');
end

% Max-min fairness style initialization under CI and constant-modulus constraints
cvx_quiet(para.cvx_quiet);
cvx_begin
variable x0(para.Ntot) complex
variable tau
maximize(tau)
subject to
real(data.Ccomm * x0) >= tau;
abs(data.FeH * x0) <= para.amp;
cvx_end

info = struct('cvx_status', cvx_status, 'cvx_optval', cvx_optval);

if ~contains(lower(cvx_status), 'solved')
    warning('Initialization CVX status: %s', cvx_status);
end
end
