function aux = compute_surrogate_terms(xt, data, para)
% COMPUTE_SURROGATE_TERMS  Build MM surrogate quantities for one outer step.
%
% Inputs:
%   xt   : Current waveform vector.
%   data : Struct generated by BUILD_DEMO_INSTANCE.
%   para : Parameter struct generated by PAPER_PARAMS.
%
% Output:
%   aux  : Struct containing the surrogate linear term gt and the
%          dominant eigenvalue bounds used by MM.
%
% Notes:
%   This function implements the surrogate construction in the TWC 2025
%   paper, especially Eqs. (40), (41b), (43), (44a), (46), and (47a).

xt_norm2 = real(xt' * xt);
px = data.P * xt;
px_energy = real(xt' * px);
% Dominant eigenvalue bound for G_t in Eq. (47a)
lambdaGt = dominant_eig_gt(px, xt, para.lambdaC);

% G_t * x_t related term in the surrogate
Gt_xt = 2 * (px_energy * px - para.lambdaC * xt_norm2 * xt);

s = data.AeH * xt;
Y = s * s';
vecY = Y(:);

% M_f,t in the compact surrogate expression
Mft = reshape(2 * (data.bdiag - data.lambdaB) .* vecY, para.M, para.M);
Mft = (Mft + Mft') / 2;

% Eigenvalue bound for M_t
lambdaMf = max(real(eig(Mft)));
lambdaMt = max(0, para.Nt * lambdaMf);
Mt_xt = data.Ae * (Mft * s);

% Final linear coefficient g_t in Eq. (47a)
gt = 2 * data.lambdaB * (Gt_xt - lambdaGt * xt) + ...
     2 * (Mt_xt - lambdaMt * xt);

aux = struct();
aux.gt = gt;
aux.lambdaGt = lambdaGt;
aux.lambdaMt = lambdaMt;
end

function lambdaGt = dominant_eig_gt(px, xt, lambdaC)
% DOMINANT_EIG_GT  Compute a low-dimensional dominant eigenvalue bound.

% Build a two-vector subspace and compute the dominant eigenvalue there
U = [px, xt];
Q = orth(U);

if isempty(Q)
    lambdaGt = 0;
    return;
end

T = 2 * (Q' * (px * px') * Q - lambdaC * Q' * (xt * xt') * Q);
lambdaGt = max(0, max(real(eig((T + T') / 2))));
end
