function out = mm_admm_isac(data, para, xt)
% MM_ADMM_ISAC  MM-ADMM-based ISAC waveform design.
%
% Inputs:
%   data : Struct generated by BUILD_DEMO_INSTANCE.
%   para : Parameter struct generated by PAPER_PARAMS.
%   xt   : Initial waveform vector in the frequency domain.
%
% Output:
%   out  : Struct containing the optimized waveform and iteration history.
%
% Notes:
%   This function implements the MM-ADMM algorithm in:
%   P. Li et al., IEEE Trans. Wireless Commun., 2025.

% Initial metrics
[isl_val, islr_val, ml_val] = compute_islr(xt, data);
history = struct();
history.isl = isl_val;
history.islr = islr_val;
history.ml = ml_val;
history.isl_db = 10 * log10(max(isl_val, eps));
history.islr_db = 10 * log10(max(islr_val, eps));
history.ml_db = 10 * log10(max(ml_val, eps));
history.inner_iters = [];
history.accepted = [];

if para.show_progress
    fprintf('[MMADMM Init] ISL = %.4f dB, ML = %.4f dB, normalized ISL = %.4f dB\n', ...
        history.isl_db(end), history.ml_db(end), history.islr_db(end));
end

islr_prev = islr_val;
for t = 1:para.outer_max
    % One outer MM step with SQUAREM acceleration
    [xt_new, state, accepted] = squarem_outer_step(xt, data, para);
    % Evaluate updated waveform
    [isl_val, islr_val, ml_val] = compute_islr(xt_new, data);
    history.isl(end+1,1) = isl_val;
    history.islr(end+1,1) = islr_val;
    history.ml(end+1,1) = ml_val;
    history.isl_db(end+1,1) = 10 * log10(max(isl_val, eps));
    history.islr_db(end+1,1) = 10 * log10(max(islr_val, eps));
    history.ml_db(end+1,1) = 10 * log10(max(ml_val, eps));
    history.accepted(end+1,1) = accepted;
    history.inner_iters(end+1,1) = state.inner_used;
    
    if para.show_progress
        fprintf('[MMADMM Outer %3d] ISL = %.4f dB, ML = %.4f dB, normalized ISL = %.4f dB, inner iters = %d, accepted = %d\n', ...
            t, history.isl_db(end), history.ml_db(end), history.islr_db(end), state.inner_used, accepted);
    end
    
    % Relative change stopping rule
    relchg = abs(islr_val - islr_prev) / max(abs(islr_prev), eps);
    xt = xt_new;
    islr_prev = islr_val;
    if relchg <= para.delta_th
        break;
    end
end

out = struct();
out.x = xt;
out.x_time = data.FeH * xt;
out.isl = history.isl(end);
out.islr = history.islr(end);
out.ml = history.ml(end);
out.isl_db = history.isl_db(end);
out.islr_db = history.islr_db(end);
out.ml_db = history.ml_db(end);
out.history = history;
end
