function [x_next, state] = one_outer_step(xt, data, para)
% ONE_OUTER_STEP  One MM outer step solved by ADMM.
%
% Inputs:
%   xt   : Current waveform vector.
%   data : Struct generated by BUILD_DEMO_INSTANCE.
%   para : Parameter struct generated by PAPER_PARAMS.
%
% Outputs:
%   x_next : Updated waveform vector.
%   state  : Struct containing the ADMM state variables.
%
% Notes:
%   The x-, z-, lambda-, and mu-updates correspond to the MM-ADMM
%   derivation in the TWC 2025 paper; see Eqs. (54), (56), and (58).

% Build surrogate terms at the current point
aux = compute_surrogate_terms(xt, data, para);

% Initialize ADMM variables in the time domain
z = data.FeH * xt;
lambda = complex(zeros(para.Ntot, 1));
mu = zeros(para.Ntot, 1);
rho = para.rho;

inner_used = 0;
x_info = struct();

for u = 1:para.inner_max
    mt = aux.gt + data.Fe * (lambda - rho * z);
    % x-subproblem: convex problem from Eq. (54)
    [x_new, x_info] = solve_x_subproblem_cvx(mt, data, para, rho);
    
    % Time-domain waveform after the x-update
    xe_new = data.FeH * x_new;

    % z-update: closed-form projection-like update, Eq. (56)
    v = xe_new + lambda / rho;
    r = para.amp - mu / rho;
    z = 0.5 * (abs(v) + r) .* exp(1j * angle(v));
    
    % Dual updates, Eq. (58)
    lambda = lambda + rho * (xe_new - z);
    mu = mu + rho * (abs(z) - para.amp);
    
    % Primal residuals for stopping
    primal1 = norm(xe_new - z, 2);
    primal2 = norm(abs(z) - para.amp, 2);
    
    % Slightly increase rho during the ADMM loop
    rho = min(rho * 1.15, 100);
    inner_used = u;
    if primal1 <= para.delta_th && primal2 <= para.delta_th
        break;
    end
end

x_next = x_new;
state = struct('z', z, 'lambda', lambda, 'mu', mu, 'rho', rho, ...
    'inner_used', inner_used, 'x_info', x_info);
end