function out = radar_wave(data, para)
% RADAR_WAVE  Radar-only reference waveform (ZC sequence).
%
% Inputs:
%   data : Struct generated by BUILD_DEMO_INSTANCE.
%   para : Parameter struct generated by PAPER_PARAMS.
%
% Output:
%   out  : Struct containing the radar-only waveform and its metrics

% Choose a beam direction and generate a beamformed ZC sequence
[~, aT] = design_theta_P0(para);
x = reshape(zc_beamformed(para.Nt, para.Nc, para.Ns, aT), [], 1);

% Normalize to the total transmit power
x = sqrt(para.PT) * x / norm(x);
% Evaluate ISL metrics
[isl_val, islr_val, ml_val] = compute_islr(x, data);

out = struct();
out.x = x;
out.x_time = data.FeH * x;
out.isl = isl_val;
out.ml = islr_val;
out.islr = ml_val;
out.isl_db = 10*log10(isl_val);
out.ml_db = 10*log10(ml_val);
out.islr_db = 10*log10(islr_val);
end