function [x, info] = solve_x_subproblem_cvx(mt, data, para, rho)
% SOLVE_X_SUBPROBLEM_CVX  Solve the x-update in the ADMM loop.
%
% Inputs:
%   mt   : Linear coefficient in the surrogate subproblem.
%   data : Struct generated by BUILD_DEMO_INSTANCE.
%   para : Parameter struct generated by PAPER_PARAMS.
%   rho  : Current ADMM penalty parameter.
%
% Outputs:
%   x    : Solution of the x-subproblem.
%   info : CVX solver information.
%
% Notes:
%   This solves the convex x-subproblem in the TWC 2025 paper, Eq. (54).

% Simple scaling to improve CVX numerical stability
obj_scale = max([1, norm(mt, inf), rho * para.PT]);
mt_s  = mt  / obj_scale;
rho_s = rho / obj_scale;

cvx_quiet(para.cvx_quiet);
cvx_begin
variable xVar(para.Ntot) complex
minimize(real(mt_s' * xVar) + (rho_s / 2) * sum_square_abs(xVar))
subject to
sum_square_abs(data.Cill * xVar) <= para.Pbar0;
real(data.Ccomm * xVar) >= data.gammaVec;
abs(data.FeH * xVar) <= para.amp;
cvx_end

x = xVar;
info = struct('cvx_status', cvx_status, 'cvx_optval', cvx_optval);

if ~contains(lower(cvx_status), 'solved')
    warning('x-subproblem CVX status: %s', cvx_status);
end
end
