function [x_out, state_out, accepted] = squarem_outer_step(x0, data, para)
% SQUAREM_OUTER_STEP  SQUAREM-accelerated outer update.
%
% Inputs:
%   x0   : Current waveform vector.
%   data : Struct generated by BUILD_DEMO_INSTANCE.
%   para : Parameter struct generated by PAPER_PARAMS.
%
% Outputs:
%   x_out     : Updated waveform vector after acceleration.
%   state_out : State returned by the final ONE_OUTER_STEP call.
%   accepted  : Flag indicating whether the extrapolated point was accepted.

% Current normalized ISL
[~, islr_x0, ~] = compute_islr(x0, data);

% Two fixed-point steps
[x1, ~] = one_outer_step(x0, data, para);
[x2, ~] = one_outer_step(x1, data, para);

% SQUAREM extrapolation quantities
r = x1 - x0;
v = x2 - 2 * x1 + x0;
nv = norm(v(:), 2);
if islr_x0 < 1e-2
    alpha = max(-norm(r(:), 2) / nv, -200);
else
    alpha = -norm(r(:), 2) / nv;
end

% Extrapolated point
x_sq = x0 - 2 * alpha * r + (alpha^2) * v;
% Accept the extrapolated point only if it improves the objective
[~, islr_sq, ~] = compute_islr(x_sq, data);
[~, islr2, ~]   = compute_islr(x2, data);

if islr_sq < islr2
    x3 = x_sq;
    accepted = 1;
else
    x3 = x2;
    accepted = 0;
end

% Finish with one standard outer step
[x_out, state_out] = one_outer_step(x3, data, para);
end