function TargetList_C = DetermineRangeVelocity_C(...
                            i_frame, ...
                            Para, ...
                            X2_Detected, ...
                            X, ...
                            IM_vel,...
                            IM_rng,...
                            QAM, ...
                            TargetList,...
                            TargetList_C_pre)
%   if i_frame=9=10n, then determine the range and velocity of C, if
% i_frame=10+10n, then determine the angle of C based on TargetList_C_pre.
%%
% make up for DstOffset and QAM
X2_Detected = circshift(X2_Detected, -(IM_rng));
X2_Detected = circshift(X2_Detected, -(IM_vel), 2);
X = circshift(X/QAM, -(IM_rng));
X = circshift(X, -(IM_vel), 2);
TargetList_C = CreatEmptyTargetList;
if mod(i_frame,Para.N_period) == Para.N_period - 1
    TargetList_All = DetermineRangeVelocity(X2_Detected, Para.N_c, Para.Nt.tot);
    % determine which is TargetList_C
    if numel(TargetList_All) ~= 1
        for i = 1:numel(TargetList_All)
            if abs(mean(TargetList_All(i).range) - TargetList.range_average) < 3 ...
                    && abs(mean(TargetList_All(i).velocity) - TargetList.velocity_average) < 3 ...
                    && abs(mean(TargetList_All(i).azi) - TargetList.azi_average) < 3
                continue
            else
                TargetList_C = TargetList_All(i);
            end
        end
    end
elseif mod(i_frame,Para.N_period) == 0
    TargetList_C = DetermineRangeVelocityAngle( ...
            TargetList_C_pre, ...
            X, ...
            X2_Detected, ...
            Para.Nt, ...
            Para.Nr, ...
            Para.N_c, ...
            Para.FoV, ...
            Para.AntSpa, ...
            'comm');
end

%   debug, when Car C leaves the line of sight of Car B, the azimuth might be
% -60 deg
if ~isempty(TargetList_C.range) && mod(i_frame, Para.N_period) ~= 9% not empty
    TargetList_C_Copy = TargetList_C;
    TargetList_C = CreatEmptyTargetList;
    NumTarget = length(TargetList_C_Copy); 
    for i = 1:NumTarget
        if abs(mean(TargetList_C_Copy(i).azi) - Para.FoV.azi(2)) < 60
            TargetList_C = TargetList_C_Copy(i);
            break
        end
    end
end

TargetList_C.label = 'C_1';
TargetList_C.orientation = 180;
TargetList_C.orientationVar = 'large';
end