function Target = InitTarget()
%%

%% |    |   Single Target case
% a = [1];
% d = [4];% distance index
% v = [4];% velocity index
% theta = [0];
%% |    |   Two Targets case
%% |    |   |   General case
% Target(1) = struct('a',1,...
%                    'd',4, ...% distance index
%                    'v', 4, ...% velocity index
%                    'ele', 0, ...
%                    'azi', 3);
% Target(2) = struct('a',1,...
%                    'd',8, ...
%                    'v', 8, ...
%                    'ele', 10, ...
%                    'azi', -14);

%% |    |   |   Extreme case
Target(1) = struct('a',1,...
                   'd',4, ...% distance index
                   'v', 6, ...% velocity index
                   'ele', -3, ...
                   'azi', 49);
Target(2) = struct('a',1,...
                   'd',6, ...
                   'v', 4, ...
                   'ele', 5, ...
                   'azi', -15);

% Target(1) = struct('a',1,...
%                    'd',4, ...% distance index
%                    'v', 4, ...% velocity index
%                    'ele', -3, ...
%                    'azi', 49);
% Target(2) = struct('a',1,...
%                    'd',5, ...
%                    'v', 5, ...
%                    'ele', 5, ...
%                    'azi', -15);
% 
% Target(1) = struct('a',1,...
%                    'd',4, ...% distance index
%                    'v', 4, ...% velocity index
%                    'ele', -3, ...
%                    'azi', 49);
% Target(2) = struct('a',1,...
%                    'd',5, ...
%                    'v', 4, ...
%                    'ele', 5, ...
%                    'azi', -15);

% Target(1) = struct('a',1,...
%                    'd',4, ...% distance index
%                    'v', 4, ...% velocity index
%                    'ele', 0, ...
%                    'azi', 0);
% Target(2) = struct('a',1,...
%                    'd',4, ...
%                    'v', 4, ...
%                    'ele', 0, ...
%                    'azi', 30);

%% |    |   |   Spectrum leakage case
% Target(1) = struct('a',1,...
%                    'd',4, ...% distance index
%                    'v', 4, ...% velocity index
%                    'ele', 15.5, ...
%                    'azi', 55.5);
end

