clear; clc
% close all
rng(666, 'twister')
addpath('Function\')

if isempty(gcp('nocreate'))   
    numWorkers = 10;      
    parpool('local', numWorkers);
end
%% 1. Initialization
Para = ParaClass();
W_f = Para.W_f;
W_c = Para.W_c;
N_c = Para.N_c;

q_deAmb = LinearPhase_Gen_DDM( ...
            Para.Nt.tot,...
            Para.N_c,...
            1);% Generate the DDMA sequence, Nt × Nc, divide N_c into Nt+1 parts
q = LinearPhase_Gen_DDM( ...
        Para.Nt.tot, ...
        Para.N_c, ...
        2);% Nt × Nc, divide N_c into Nt parts
Gain_RDM = zeros(Para.N_frame+1, Para.Nt.tot, Para.Nr.tot);% used to save channel gain and demod QAM symbol
range_average = zeros(Para.N_frame+1);
velocity_average = zeros(Para.N_frame+2);

% all data and data estimated by comm receiver
[DataAll, DataEstAll] = DataGen(Para);
% Save all the data in the tracking
% [ParaAll_B, ParaAll_B, Sys] = ParaAllGen(Para.N_frame);
% all the carcenter in the tracking process
Sys.CarCenter = zeros(Para.N_frame, 3, 3);% column->x,y,z; row->A,B,C
Sys.beta = zeros(4, Para.N_frame);
TargetList_C = CreatEmptyTargetList;
%% 2. Initial Sensing
TDData_B = TDDataGen(Para, q_deAmb, 'comm');
X2_sum = zeros(Para.N_f, Para.N_c);
for i_r = 0:Para.Nr.tot-1                                                              
    % if there is more than 1 Rx antenna, X2 need non-coherent
    X = fftshift(fft( ...
            fft(TDData_B(:,:,i_r+1).*W_f).*W_c, ...
            N_c, ...
            2),...
            2);
    X2_sum = X2_sum + X.*conj(X);    
end
X2_sum = X2_sum/Para.Nr.tot;
X2_Detected = CFAR(2, X2_sum, Para.RDM_CFAR, Para.SNRdB, 'CA');
% Determine range and velocity
TargetList_ini = DetermineRangeVelocity(X2_Detected, Para.N_c, Para.Nt.tot);

% Determine angle
Para = Para.ParaUpd();
TDData_B = TDDataGen(Para, q, 'comm');
X2_sum = zeros(Para.N_f, Para.N_c);
X = zeros(Para.N_f, Para.N_c, Para.Nr.tot);
for i_r = 0:Para.Nr.tot-1
    % if there is more than 1 Rx antenna, X2 need non-coherent
    X(:,:,i_r+1) = fftshift(...
                    fft(fft(TDData_B(:,:,i_r+1).*W_f).*W_c, N_c, 2),...
                    2);
    X2_sum = X2_sum + X(:,:,i_r+1).*conj(X(:,:,i_r+1));    
end
X2_sum = X2_sum/Para.Nr.tot;
X2_Detected = CFAR(2, X2_sum, Para.RDM_CFAR, Para.SNRdB, 'CA');

TargetList_ini = DetermineRangeVelocityAngle( ...
            TargetList_ini, ...
            X, ...
            X2_Detected, ...
            Para.Nt, ...
            Para.Nr, ...
            Para.N_c, ...
            Para.FoV, ...
            Para.AntSpa, ...
            'comm');
% Determine the label of target
TargetList_ini = DetermineLabel_ini(TargetList_ini, Para, 'comm');
%% 3. Determine Orientation
% Wait for Para.N_period frames
for i = 1:Para.N_period-2
    Para = Para.ParaUpd();
end

Para = Para.ParaUpd();
TDData_B = TDDataGen(Para, q_deAmb, 'comm');
X2_sum = zeros(Para.N_f, Para.N_c);
for i_r = 0:Para.Nr.tot-1
    % if there is more than 1 Rx antenna, X2 need non-coherent
    X = fftshift(fft( ...
            fft(TDData_B(:,:,i_r+1).*W_f).*W_c, ...
            N_c, ...
            2),...
            2);
    X2_sum = X2_sum + X.*conj(X);    
end
X2_sum = X2_sum/Para.Nr.tot;
X2_Detected = CFAR(2, X2_sum, Para.RDM_CFAR, Para.SNRdB, 'CA');
% Determine range and velocity
TargetList_ort = DetermineRangeVelocity(X2_Detected, Para.N_c, Para.Nt.tot);

% Determine angle
Para = Para.ParaUpd();
TDData_B = TDDataGen(Para, q, 'comm');
X2_sum = zeros(Para.N_f, Para.N_c);
X = zeros(Para.N_f, Para.N_c, Para.Nr.tot);
X_nowin = zeros(Para.N_f, Para.N_c, Para.Nr.tot);

for i_r = 0:Para.Nr.tot-1
    % if there is more than 1 Rx antenna, X2 need non-coherent
    X(:,:,i_r+1) = fftshift(...
                    fft(fft(TDData_B(:,:,i_r+1).*W_f).*W_c, N_c, 2),...
                    2);
    X_nowin(:,:,i_r+1) = fftshift(...
                    fft(fft(TDData_B(:,:,i_r+1)), N_c, 2),...
                    2);
    X2_sum = X2_sum + X(:,:,i_r+1).*conj(X(:,:,i_r+1));    
end
X2_sum = X2_sum/Para.Nr.tot;
X2_Detected = CFAR(2, X2_sum, Para.RDM_CFAR, Para.SNRdB, 'CA');

% Determine angle
TargetList_ort = DetermineRangeVelocityAngle( ...
            TargetList_ort, ...
            X_nowin,...
            X2_Detected, ...
            Para.Nt, ...
            Para.Nr, ...
            Para.N_c, ...
            Para.FoV, ...
            Para.AntSpa, ...
            'comm');
% Determine the label of target
TargetList_ort = DetermineLabel(TargetList_ini, TargetList_ort, Para);
% Detemine Orientation
TargetList_ort = DetermineOrientation_ini(TargetList_ini, TargetList_ort, Para, 'comm');
% Determine channel gain
Gain_RDM(1,:,:) = DetermineGain(X_nowin, TargetList_ort, Para);
%% 4. Tracking
KF(Para.N_frame) = ...
    struct( ...
    'label',[],...
    'mu', [], ...
    'var', []);

% Determine the initial value of KF
KF_ini = DetermineKF_ini(TargetList_ort, Para, 'comm');
 
for i = 1:Para.N_frame
    % if i == 230
    %     pause
    % end
    disp('---------------------------------------------------------------')
    disp(['Current frame = ' num2str(i)])
    fprintf('IM_rng                         = %4.2f\n', DataAll.IM_rng(i))
    fprintf('IM_vel                         = %4.2f\n', DataAll.IM_vel(i))
    disp('||||||||||||||||||||||||||||||||||')
    Para = Para.ParaUpd();
    % save results
    Sys.CarCenter(i,:,:) = Para.CarCenter;
    Sys.beta(:,i) = Para.beta;    
    ParaAll_B.EachFrameReal(i*2-1:i*2) = Para.Target_B;  
    if mod(i,Para.N_period) == Para.N_period - 1
        if i > Para.N_period*Para.N_period_VelStartTxInfo
            TDData_B = TDDataGen(Para, q_deAmb, 'comm', DataAll.QAM(i), DataAll.IM_rng(i), DataAll.IM_vel(i));
        else
            TDData_B = TDDataGen(Para, q_deAmb, 'comm', DataAll.QAM(i), DataAll.IM_rng(i), 0);
        end
%         TDData_B = TDDataGen(Para, q, 'comm', DataAll.QAM(i), DataAll.DstOffset(i));
    else
        if i > Para.N_period*Para.N_period_VelStartTxInfo
            TDData_B = TDDataGen(Para, q, 'comm', DataAll.QAM(i), DataAll.IM_rng(i), DataAll.IM_vel(i));
        else
            TDData_B = TDDataGen(Para, q, 'comm', DataAll.QAM(i), DataAll.IM_rng(i), 0);
        end
    end    
    % Obtain RDM
    X2_sum = zeros(Para.N_f, Para.N_c);
    X = zeros(Para.N_f, Para.N_c, Para.Nr.tot);
    X_nowin = zeros(Para.N_f, Para.N_c, Para.Nr.tot);
    parfor i_r = 0:Para.Nr.tot-1
        % if there is more than 1 Rx antenna, X2 need non-coherent
        X(:,:,i_r+1) = fftshift(fft(fft(TDData_B(:,:,i_r+1).*W_f)...
                       .*W_c, N_c, 2),...
                       2);
        X_nowin(:,:,i_r+1) = fftshift(fft(fft(TDData_B(:,:,i_r+1))...
                       , N_c, 2),...
                       2);
        X2_sum = X2_sum + X(:,:,i_r+1).*conj(X(:,:,i_r+1));    
    end
    X2_sum = X2_sum/Para.Nr.tot;        
    X2_Detected = CFAR(2, X2_sum, Para.RDM_CFAR, Para.SNRdB, 'CA');

    % Determine all information, including bit, range, velocity, angle of
    % arrival, label and orientation    
    if i == 1
        TargetList_input = TargetList_ort;
        KF_input = KF_ini;
    elseif i <= Para.orientation_RefNum * Para.N_period
        TargetList_input = ParaAll_B.EachFrameEst;
        KF_input = KF(i-1);
    else% i > Para.orientation_RefNum * Para.N_period
        TargetList_input = ParaAll_B.EachFrameEst(...
            i-Para.orientation_RefNum * Para.N_period : i-1 ...
            );
        KF_input = KF(i-1);
    end
    [TargetList, ...
     DataEstAll.QAM(i), ...
     DataEstAll.IM_rng(i),...
     DataEstAll.IM_vel(i),...
     Gain_RDM(i+1,:,:),...
     range_average(i+1),...
     velocity_average(i+2)] = ... 
                     DetermineAll_A( ...
                     i, ...
                     X2_Detected, ...
                     Para, ...
                     X, ...
                     TDData_B,...
                     KF_input, ...
                     squeeze(Gain_RDM(i,:,:)),...
                     TargetList_input,...
                     range_average(i),...
                     velocity_average(i:i+1));

    if mod(i,Para.N_period) == Para.N_period - 1 || mod(i,Para.N_period) == 0 % i = 9 + 10n or i = 10 + 10n
        TargetList_C = DetermineRangeVelocity_C(...
                            i, ...
                            Para, ...
                            X2_Detected, ...
                            X, ...
                            DataEstAll.IM_vel(i),...
                            DataEstAll.IM_rng(i),...
                            DataEstAll.QAM(i), ...
                            TargetList,...
                            TargetList_C);
    end      
    % combine target A and target C
    if numel(TargetList_C.range) ~= 0 && mod(i,Para.N_period) == 0
        ParaAll_B.EachFrameEst(i).TargetList = [TargetList TargetList_C];  
        % reset
        TargetList_C = CreatEmptyTargetList;
    else
        ParaAll_B.EachFrameEst(i).TargetList = TargetList;  
    end

    % tracking
    if i ~= 1
        KF(i) = Tracking_B(...
            Para,...
            i,...                           
            ParaAll_B.EachFrameEst(i).TargetList,...
            KF(i-1) );        
    else% i == 1
        KF(i) = Tracking_B(...
            Para,...
            i,...                           
            ParaAll_B.EachFrameEst(i).TargetList,...
            KF_ini);              
    end   
%% |   Print Info      
    fprintf('IM_rng_est - IM_rng = %2d\n', DataEstAll.IM_rng(i) - DataAll.IM_rng(i));
    fprintf('IM_vel_est - IM_vel = %2d\n', DataEstAll.IM_vel(i) - DataAll.IM_vel(i));
    fprintf('|QAM_est   - QAM   |= %2.1f\n', abs(DataAll.QAM(i)-DataEstAll.QAM(i)));
    if (abs(DataAll.QAM(i)-DataEstAll.QAM(i)) ~= 0 || ...
            DataEstAll.IM_rng(i) - DataAll.IM_rng(i) ~= 0 || DataEstAll.IM_vel(i) - DataAll.IM_vel(i) ~=0) ...
            && i>100
        error('error!')
    end
    fprintf('orientation         = %2.1f\n', TargetList.orientation);
    if DataEstAll.IM_rng(i) - DataAll.IM_rng(i) ~= 0 || DataEstAll.IM_vel(i) - DataAll.IM_vel(i) ~= 0
        disp('pause')
    end
end
figure;hold on;
subplot(3,1,1); plot((DataAll.IM_rng-DataEstAll.IM_rng))
subplot(3,1,2); plot((DataAll.IM_vel-DataEstAll.IM_vel))
subplot(3,1,3); plot(abs(DataAll.QAM-DataEstAll.QAM))
%% 5. Save and Plot
% save('Data\InfoFusion\CT_track_P_5dBm_KF_new.mat', ...
%     "Para",...
%     "KF",...
%     "Sys",...
%     "ParaAll_B" ...
%     );
% PerformanceEvaluation