clear; clc
% close all
rng(666, 'twister')
addpath('Function\')

if isempty(gcp('nocreate'))   
    numWorkers = 10;      
    parpool('local', numWorkers);
end
%% 1. Initialization
Para = ParaClass();
q_deAmb = LinearPhase_Gen_DDM( ...
            Para.Nt.tot,...
            Para.N_c,...
            1);% Generate the DDMA sequence, Nt × Nc, divide N_c into Nt+1 parts
q = LinearPhase_Gen_DDM( ...
        Para.Nt.tot, ...
        Para.N_c, ...
        2);% Nt × Nc, divide N_c into Nt parts

% all data and data estimated by comm receiver
[DataAll, DataEstAll] = DataGen(Para);
% Save all the data in the tracking
% [ParaAll_A, ParaAll_B, Sys] = ParaAllGen(Para.N_frame);
% all the carcenter in the tracking process
Sys.CarCenter = zeros(Para.N_frame, 3, 3);% column->x,y,z; row->A,B,C
Sys.beta = zeros(4, Para.N_frame);
%% 2. Initial Sensing
TDData_A = TDDataGen(Para, q_deAmb, 'radar');
X2_sum = zeros(Para.N_f, Para.N_c);
for i_r = 0:Para.Nr.tot-1
    % if there is more than 1 Rx antenna, X2 need non-coherent
    X = fftshift(fft( ...
            fft(TDData_A(:,:,i_r+1).*Para.W_f).*Para.W_c, ...
            Para.N_c, ...
            2),...
            2);
    X2_sum = X2_sum + X.*conj(X);    
end
X2_sum = X2_sum/Para.Nr.tot;
X2_Detected = CFAR(2, X2_sum, Para.RDM_CFAR, Para.SNRdB, 'CA');
% Determine range and velocity
TargetList_ini = DetermineRangeVelocity(X2_Detected, Para.N_c, Para.Nt.tot);

% Determine angle
Para = Para.ParaUpd();
TDData_A = TDDataGen(Para, q, 'radar');
X2_sum = zeros(Para.N_f, Para.N_c);
X = zeros(Para.N_f, Para.N_c, Para.Nr.tot);
for i_r = 0:Para.Nr.tot-1
    % if there is more than 1 Rx antenna, X2 need non-coherent
    X(:,:,i_r+1) = fftshift(...
                    fft(fft(TDData_A(:,:,i_r+1).*Para.W_f).*Para.W_c, Para.N_c, 2),...
                    2);
    X2_sum = X2_sum + X(:,:,i_r+1).*conj(X(:,:,i_r+1));    
end
X2_sum = X2_sum/Para.Nr.tot;
X2_Detected = CFAR(2, X2_sum, Para.RDM_CFAR, Para.SNRdB, 'CA');

% Determine angle
TargetList_ini = DetermineRangeVelocityAngle( ...
            TargetList_ini, ...
            X, ...
            X2_Detected, ...
            Para.Nt, ...
            Para.Nr, ...
            Para.N_c, ...
            Para.FoV, ...
            Para.AntSpa, ...
            'radar');
% Determine the label of target
TargetList_ini = DetermineLabel_ini(TargetList_ini, Para, 'radar');
%% 3. Determine Orientation
% Wait for Para.N_period frames
for i = 1:Para.N_period-2
    Para = Para.ParaUpd();
end

Para = Para.ParaUpd();
TDData_A = TDDataGen(Para, q_deAmb, 'radar');
X2_sum = zeros(Para.N_f, Para.N_c);
for i_r = 0:Para.Nr.tot-1
    % if there is more than 1 Rx antenna, X2 need non-coherent
    X = fftshift(fft( ...
            fft(TDData_A(:,:,i_r+1).*Para.W_f).*Para.W_c, ...
            Para.N_c, ...
            2),...
            2);
    X2_sum = X2_sum + X.*conj(X);    
end
X2_sum = X2_sum/Para.Nr.tot;
X2_Detected = CFAR(2, X2_sum, Para.RDM_CFAR, Para.SNRdB, 'CA');
% Determine range and velocity
TargetList_ort = DetermineRangeVelocity(X2_Detected, Para.N_c, Para.Nt.tot);

% Determine angle
Para = Para.ParaUpd();
TDData_A = TDDataGen(Para, q, 'radar');
X2_sum = zeros(Para.N_f, Para.N_c);
X = zeros(Para.N_f, Para.N_c, Para.Nr.tot);
for i_r = 0:Para.Nr.tot-1
    % if there is more than 1 Rx antenna, X2 need non-coherent
    X(:,:,i_r+1) = fftshift(...
                    fft(fft(TDData_A(:,:,i_r+1).*Para.W_f).*Para.W_c, Para.N_c, 2),...
                    2);
    X2_sum = X2_sum + X(:,:,i_r+1).*conj(X(:,:,i_r+1));    
end
X2_sum = X2_sum/Para.Nr.tot;
X2_Detected = CFAR(2, X2_sum, Para.RDM_CFAR, Para.SNRdB, 'CA');

% Determine angle
TargetList_ort = DetermineRangeVelocityAngle( ...
            TargetList_ort, ...
            X, ...
            X2_Detected, ...
            Para.Nt, ...
            Para.Nr, ...
            Para.N_c, ...
            Para.FoV, ...
            Para.AntSpa, ...
            'radar');
% Determine the label of target
TargetList_ort = DetermineLabel(TargetList_ini, TargetList_ort, Para);
% Detemine Orientation
TargetList_ort = DetermineOrientation_ini(TargetList_ini, TargetList_ort, Para, 'radar');
%% 4. Tracking
KF(Para.N_frame/Para.N_period) = ...
    struct( ...
    'label',[],...
    'mu', [], ...
    'var', []);

% first frame
Sys.CarCenter(1,:,:) = Para.CarCenter;
Sys.beta(:,1) = Para.beta;

% Determine the initial value of KF
KF_ini = DetermineKF_ini(TargetList_ort, Para, 'radar');
 
for i = 1:Para.N_frame
    disp(['Current frame = ' num2str(i)])
    Para = Para.ParaUpd();
    % save results
    Sys.CarCenter(i,:,:) = Para.CarCenter;
    Sys.beta(:,i) = Para.beta;    
    ParaAll_A.EachFrameReal(i*2-1:i*2) = Para.Target_A;

    if mod(i-1,Para.N_period) == 8
%%  |   Nc/(Nt+1) in the tracking process, used to de-ambiguity of velocity
        TDData_A = TDDataGen(Para, q_deAmb, 'radar', DataAll.QAM(i), DataAll.IM_rng(i), DataAll.IM_vel(i)); 
        % Convert distance to seq
        DstOffsetInverseSeq = exp(-1j*2*pi*((0:Para.N_f-1).'* ...
                        (DataAll.IM_rng(i)*ones(1,Para.N_c))...
                        /Para.N_f));
        VelOffsetInverseSeq = exp(-1j*2*pi*((DataAll.IM_vel(i)*ones(Para.N_f,1))* ...
                        (0:Para.N_c-1)...
                        /Para.N_c));

        % Obtain RDM
        X2_sum = zeros(Para.N_f, Para.N_c);
        X = zeros(Para.N_f, Para.N_c, Para.Nr.tot);
        for i_r = 0:Para.Nr.tot-1
            % if there is more than 1 Rx antenna, X2 need non-coherent
            X(:,:,i_r+1) = fftshift(fft(fft(TDData_A(:,:,i_r+1).*Para.W_f...
                           .*conj(DataAll.QAM(i))...
                           .*DstOffsetInverseSeq)...
                           .*VelOffsetInverseSeq...
                           .*Para.W_c, Para.N_c, 2),...
                           2);
            X2_sum = X2_sum + X(:,:,i_r+1).*conj(X(:,:,i_r+1));    
        end
        X2_sum = X2_sum/Para.Nr.tot;        

        X2_Detected = CFAR(2, X2_sum, Para.RDM_CFAR, Para.SNRdB, 'CA');
        
        % Determine range and velocity
        TargetList = DetermineRangeVelocity(X2_Detected, Para.N_c, Para.Nt.tot);
%         if mean([TargetList.range] ) <100
%             disp('error!')
%         end        
    elseif mod(i-1,Para.N_period) == 9
%%  |   Information fusion
        TDData_A = TDDataGen(Para, q, 'radar', DataAll.QAM(i), DataAll.IM_rng(i), DataAll.IM_vel(i));
        DstOffsetInverseSeq = exp(-1j*2*pi*((0:Para.N_f-1).'* ...
                        (DataAll.IM_rng(i)*ones(1,Para.N_c))...
                        /Para.N_f));
        VelOffsetInverseSeq = exp(-1j*2*pi*((DataAll.IM_vel(i)*ones(Para.N_f,1))* ...
                        (0:Para.N_c-1)...
                        /Para.N_c));

        % Obtain RDM
        X2_sum = zeros(Para.N_f, Para.N_c);
        X = zeros(Para.N_f, Para.N_c, Para.Nr.tot);
        for i_r = 0:Para.Nr.tot-1
            % if there is more than 1 Rx antenna, X2 need non-coherent
            X(:,:,i_r+1) = fftshift(fft(fft(TDData_A(:,:,i_r+1).*Para.W_f...
                           *conj(DataAll.QAM(i))...
                           .*DstOffsetInverseSeq)...
                           .*VelOffsetInverseSeq ...
                           .*Para.W_c, Para.N_c, 2),...
                           2);
            X2_sum = X2_sum + X(:,:,i_r+1).*conj(X(:,:,i_r+1));    
        end
        X2_sum = X2_sum/Para.Nr.tot;
        X2_Detected = CFAR(2, X2_sum, Para.RDM_CFAR, Para.SNRdB, 'CA');
        
        % Determine angle
        TargetList = DetermineRangeVelocityAngle( ...
                    TargetList, ...
                    X, ...
                    X2_Detected, ...
                    Para.Nt, ...
                    Para.Nr, ...
                    Para.N_c, ...
                    Para.FoV, ...
                    Para.AntSpa, ...
                    'radar'); 
        ParaAll_A.EachPeriodEst(i/Para.N_period).TargetList = TargetList;
        % Determine Label
        if i == Para.N_period           
            ParaAll_A.EachPeriodEst(i/Para.N_period).TargetList = ...
                        DetermineLabel(TargetList_ort, ...
                        ParaAll_A.EachPeriodEst(i/Para.N_period).TargetList, ...
                        Para);
        else
            ParaAll_A.EachPeriodEst(i/Para.N_period).TargetList = ...
                        DetermineLabel(ParaAll_A.EachPeriodEst(i/Para.N_period - 1).TargetList, ...
                        ParaAll_A.EachPeriodEst(i/Para.N_period).TargetList, ...
                        Para);
        end
        % Determine Orientation        
        if i/Para.N_period >= Para.orientation_RefNum
            ParaAll_A.EachPeriodEst(i/Para.N_period).TargetList = ...
                        DetermineOrientation( ...
                        ParaAll_A.EachPeriodEst(i/Para.N_period-(Para.orientation_RefNum-1):i/Para.N_period), ...
                        Para, ...
                        'radar');
        else
            ParaAll_A.EachPeriodEst(i/Para.N_period).TargetList = ...
                        DetermineOrientation( ...
                        ParaAll_A.EachPeriodEst, ...
                        Para, ...
                        'radar');
        end
             
%         KF(i/Para.N_period) = Tracking_A(...
%                             o, ...
%                             ParaAll_A.EachPeriodEst,...
%                             KF(i/Para.N_period - 1),...
%                             Para,...
%                             i/Para.N_period); 
        
        if i == Para.N_period
            KF(1) = Tracking_A(...
                Para,...
                i/Para.N_period,...                
                KF_ini,...
                ParaAll_A.EachPeriodEst(i/Para.N_period).TargetList,...
                KF(1:(i/Para.N_period - 1)));
        else
            KF(i/Para.N_period) = Tracking_A(...
                Para,...
                i/Para.N_period,...               
                KF(i/Para.N_period-1),...
                ParaAll_A.EachPeriodEst(i/Para.N_period).TargetList,...
                KF(max(1,(i/Para.N_period-floor(Para.orientation_RefNum/2))) : (i/Para.N_period-1)));
        end
    else 
        continue
    end            
  
%% |   Print Info   
end
%% 5. Save and Plot
% save('Data\InfoFusion\RT_track_P_5dBm_CovPred_AlwaysLow.mat', ...
%     "Para",...
%     "KF",...
%     "Sys",...
%     "ParaAll_A" ...
%     );
% PerformanceEvaluation