function [subframeMod, subframeDemod, subframeInfo] = createModDemod(onlyData, ofdm, antennas)

    if onlyData
      % Create OFDM modulator for subframe A (contains only data)
      subframeMod = comm.OFDMModulator(...
          "CyclicPrefixLength", ofdm.cyclicPrefixLength, ...
          "FFTLength", ofdm.Nsub, ...
          "NumGuardBandCarriers", ofdm.numGuardBandCarriers, ...
          "NumTransmitAntennas", antennas.Ntx, ...
          "NumSymbols", ofdm.subframeALength);

    else
      % Create OFDM modulator for subframe B (contains pilots and data)
      subframeMod = comm.OFDMModulator(...
          "CyclicPrefixLength", ofdm.cyclicPrefixLength,...
          "FFTLength", ofdm.Nsub, ...
          "NumGuardBandCarriers", ofdm.numGuardBandCarriers,...
          "NumTransmitAntennas", antennas.Ntx,...
          "NumSymbols", ofdm.subframeBLength,...
          "PilotCarrierIndices", ofdm.pilotIdxs, ...
          "PilotInputPort", true);
    end
    % Get information about the subframe modulator
    subframeInfo = info(subframeMod);

    % Create OFDM demodulator for subframe
    subframeDemod = comm.OFDMDemodulator(subframeMod);
    subframeDemod.NumReceiveAntennas = antennas.Nrx;
end