function [ParaAll_A, ParaAll_B, Sys] = ParaAllGen(N_frame)

TargetList = struct('range', [], ...
                    'velocity', [],...
                    'azi', [],...
                    'ele', [],...
                    ...
                    'range_average',[],...
                    'velocity_average', [],...
                    'azi_average', [],...
                    'ele_average', [],...
                    ...
                    'range_variance',[],...
                    'velocity_variance', [],...
                    'azi_variance',[], ...
                    'ele_variance',[]);

% radar and comm tracking results
ParaAll_A.ParaEstAll(N_frame) = TargetList;
ParaAll_B.ParaEstAll(N_frame) = TargetList;

% all the real target info in the tracking process
ParaAll_A.Target(N_frame) = struct(...
   'a',[],...
   'fr',[], ...
   'fv',[], ...
   'ele',[], ...% for simplicity
   'azi',[]);
ParaAll_B.Target(N_frame) = struct(...
   'a',[],...
   'fr',[], ...
   'fv',[], ...
   'ele',[], ...% for simplicity
   'azi',[]);

% all the carcenter in the tracking process
Sys.CarCenter = zeros(N_frame, 3, 3);% column->x,y,z; row->A,B,C
Sys.beta = zeros(4, N_frame);
end

