# Codacy (and in turn prospector) apparently enables _all_ rules available in
# pydocstyle by default [1].
# This configures pep257 on prospector to use the default conventions according
# to the pep257 docs [2].
#
# [1] https://community.codacy.com/t/d203-and-d213-are-not-required-by-pep-257/237/7)
# [2] http://www.pydocstyle.org/en/stable/error_codes.html#default-conventions

pep257:
  disable:
    - D203
    - D212
    - D213
    - D214
    - D215
    - D404
    - D405
    - D406
    - D407
    - D408
    - D409
    - D410
    - D411
    - D413
    - D415
    - D416
    - D417
