#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
#matlab -nodisplay -r "addpath(genpath('.')); mex -setup -C++"

matlab -nodisplay -r "addpath(genpath('.')); mex rir_generator.cpp rir_generator_core.cpp"
  

matlab -nodisplay -r "addpath(genpath('.')); LoopWrapperMain"
