% clear;clc
% close all
addpath('..')
addpath('..\Function\')
load('..\Data\InfoFusion\CT_track_P_5dBm_KF_new.mat')
%% Re-organize the fusion resluts
% used to compare with Rectangular coordinate system parameters in system object 'Para'

% extract info of fusion results into array for visualization.
% every KF4plot represents a target.
% every column in KF4plot represents a period.
KF4plot = ...
    struct( ...
    'label',[],...
    'frame',[],...
    'mu', [], ...
    'var', []);
for i = 1:Para.N_frame
    % if KF(i).label doesn't exist in KF4plot, then add it in
    KF4plot(1).label = 'A_0';
    KF4plot(1).frame = 1:Para.N_frame;
    KF4plot(1).mu = [KF4plot(1).mu KF(i).mu];
    KF4plot(1).var = [KF4plot(1).var reshape(KF(i).var, [], 1)];
end
%% Re-organize the measurement results
% used to compare with polar-domain coordinate system parameters of 'ParaAll_B.EachFrameReal'

% extract info of fusion results into array for visualization.
% every Meas4plot represents a target.
% every column in KF4plot represents a period.
Meas4plot = ...
    struct( ...
    'label',[],...
    'frame',[],...
    'range', [], ...
    'velocity', [], ...
    'azi', []);
for i = 1:Para.N_frame
    %   if 'ParaAll_B.EachFrameEst(i).TargetList(:).label' doesn't exist in 
    % Meas4plot, then add it in
    AllLabel_i = char(ParaAll_B.EachFrameEst(i).TargetList(:).label);
    for j = 1:size(AllLabel_i, 1)
    % j-th target in i-th period of 'ParaAll_B.EachFrameEst'
        if isempty([Meas4plot.label])
        % if KF4plot is empty, then add the new target info into it unconditionally
            Meas4plot(1).label = AllLabel_i(j,:);
            Meas4plot(1).frame = i;
            Meas4plot(1).range = ParaAll_B.EachFrameEst(i).TargetList(j).range_average;
            Meas4plot(1).velocity = ParaAll_B.EachFrameEst(i).TargetList(j).velocity_average;
            Meas4plot(1).azi = ParaAll_B.EachFrameEst(i).TargetList(j).azi_average;
        else
        %   if Meas4plot is not empty, then determine if AllLabel_i(j,:) is in
        % Meas4plot.
        %   if yes, determine the index in Meas4plot and add the info of
        % 'j-th target in i-th period' in.
        %   if not, add a new struct of Meas4plot.
            index = find (...
                        all( repmat(AllLabel_i(j,:), numel(Meas4plot), 1)...
                        == char(Meas4plot(:).label) , 2)...
                        );
            if isempty(index)
                Meas4plot(numel(Meas4plot)+1).label = AllLabel_i(j,:);
                Meas4plot(numel(Meas4plot)).frame = i;
                if strcmp(AllLabel_i(j,:), 'A_0')
                    Meas4plot(numel(Meas4plot)).range = ParaAll_B.EachFrameEst(i).TargetList(j).range_average;
                    Meas4plot(numel(Meas4plot)).velocity = ParaAll_B.EachFrameEst(i).TargetList(j).velocity_average;
                    Meas4plot(numel(Meas4plot)).azi = ParaAll_B.EachFrameEst(i).TargetList(j).azi_average;
                else
                    Meas4plot(numel(Meas4plot)).range = mean(ParaAll_B.EachFrameEst(i).TargetList(j).range);
                    Meas4plot(numel(Meas4plot)).velocity = mean(ParaAll_B.EachFrameEst(i).TargetList(j).velocity);
                    Meas4plot(numel(Meas4plot)).azi = mean(ParaAll_B.EachFrameEst(i).TargetList(j).azi);
                end
            else      
                if strcmp(AllLabel_i(j,:), 'A_0')
                    Meas4plot(index).frame = [Meas4plot(index).frame, ...
                                            i];
                    Meas4plot(index).range = [Meas4plot(index).range,...
                                        ParaAll_B.EachFrameEst(i).TargetList(j).range_average];
                    Meas4plot(index).velocity = [Meas4plot(index).velocity,...
                                        ParaAll_B.EachFrameEst(i).TargetList(j).velocity_average];
                    Meas4plot(index).azi = [Meas4plot(index).azi,...
                                        ParaAll_B.EachFrameEst(i).TargetList(j).azi_average];
                else
                    Meas4plot(index).frame = [Meas4plot(index).frame, ...
                                        i];
                    Meas4plot(index).range = [Meas4plot(index).range,...
                                        mean(ParaAll_B.EachFrameEst(i).TargetList(j).range)];
                    Meas4plot(index).velocity = [Meas4plot(index).velocity,...
                                        mean(ParaAll_B.EachFrameEst(i).TargetList(j).velocity)];
                    Meas4plot(index).azi = [Meas4plot(index).azi,...
                                        mean(ParaAll_B.EachFrameEst(i).TargetList(j).azi)];
                end
            end
        end
        
    end
end
%% Obtain the estimated results of orientation
Orientation4plot = ...
    struct( ...
    'label',[],...
    'frame',[],...
    'value', []);
for i = 1:Para.N_frame
    %   if 'ParaAll_B.EachFrameEst(i).TargetList(:).label' doesn't exist in 
    % Meas4plot, then add it in
    AllLabel_i = char(ParaAll_B.EachFrameEst(i).TargetList(:).label);
    for j = 1:size(AllLabel_i, 1)
    % j-th target in i-th period of 'ParaAll_B.EachFrameEst'
        if isempty([Orientation4plot.label])
        % if KF4plot is empty, then add the new target info into it unconditionally
            Orientation4plot(1).label = AllLabel_i(j,:);
            Orientation4plot(1).period = i;
            Orientation4plot(1).value = ParaAll_B.EachFrameEst(i).TargetList(j).orientation;
        else
        %   if Meas4plot is not empty, then determine if AllLabel_i(j,:) is in
        % Meas4plot.
        %   if yes, determine the index in Meas4plot and add the info of
        % 'j-th target in i-th period' in.
        %   if not, add a new struct of Meas4plot.
            index = find (...
                        all( repmat(AllLabel_i(j,:), numel(Orientation4plot), 1)...
                        == char(Orientation4plot(:).label) , 2)...
                        );
            if isempty(index)
                Orientation4plot(numel(Orientation4plot)+1).label = AllLabel_i(j,:);
                Orientation4plot(numel(Orientation4plot)).period = i;
                Orientation4plot(numel(Orientation4plot)).value = ParaAll_B.EachFrameEst(i).TargetList(j).orientation;
            else                
                Orientation4plot(index).period = [Orientation4plot(index).period, ...
                                        i];
                Orientation4plot(index).value = [Orientation4plot(index).value,...
                                    ParaAll_B.EachFrameEst(i).TargetList(j).orientation];
            end
        end
        
    end    
end
%% Performance evaluation of parameters that can be estimated both in measurement and state
%% |    range
figure; 
title('Comparison between Fusion Results and Measurements')
subplot(3,1,1); set(0,'defaultfigurecolor','w') ;set(gca,'FontName','Times New Roman','FontSize',10);
box on; grid on;hold on; xlabel('Frame','FontName','Times New Roman','FontSize',14);ylabel('Distance [m]','FontName','Times New Roman','FontSize',14)
% Fusion results
p1 = plot(KF4plot(1).frame, sqrt(KF4plot(1).mu(1,:).^2 + KF4plot(1).mu(2,:).^2), ...
    'b-', 'LineWidth', 1, 'MarkerSize', 6);

% Measured results
p2 = plot(Meas4plot(1).frame, (Meas4plot(1).range-1) ./ (2*Para.fs*Para.TcEff/...
            (3e8 * 2*(Para.Tsen+Para.Tcom))), ...
    'r-', 'LineWidth', 1, 'MarkerSize', 6);
p3 = plot(Meas4plot(2).frame, Meas4plot(2).range./ (2*Para.fs*Para.TcEff/...
            (3e8 * 2*(Para.Tsen+Para.Tcom))), ...
    'rs', 'LineWidth', 1, 'MarkerSize', 6);

% True 
p4 = plot(1:Para.N_frame, Distance(...
                                    Sys.CarCenter(1:Para.N_frame, 1, :),...
                                    Sys.CarCenter(1:Para.N_frame, 2, :)), ...
    'g-', 'LineWidth', 1, 'MarkerSize', 6);
p5 = plot(1:Para.N_frame, Distance(...
                                    Sys.CarCenter(1:Para.N_frame, 2, :),...
                                    Sys.CarCenter(1:Para.N_frame, 3, :)) ...
                                    + Distance(...
                                    Sys.CarCenter(1:Para.N_frame, 1, :),...
                                    Sys.CarCenter(1:Para.N_frame, 3, :)), ...
    'g--', 'LineWidth', 1, 'MarkerSize', 6);

ah=axes('position',get(gca,'position'),'visible','off'); 
l1 = legend(ah, [p1, p2, p3],...
    {'Fused-Vehicle 1',...
    'Measured-Vehicle 1', ...
    'Measured-Vehicle 3'},...
    'Box','off');
l1.FontSize = 14;    
l1.FontName = 'Times New Roman';
%% |    azimuth
subplot(3,1,2); set(0,'defaultfigurecolor','w') ;set(gca,'FontName','Times New Roman','FontSize',10);
box on; grid on; hold on; xlabel('Frame','FontName','Times New Roman','FontSize',14);ylabel('Azimuth [deg]','FontName','Times New Roman','FontSize',14)
% Fusion results
plot(KF4plot(1).frame, asind( KF4plot(1).mu(1,:) ...
                                    ./ sqrt(KF4plot(1).mu(1,:).^2 + KF4plot(1).mu(2,:).^2)), ...
    'b-', 'LineWidth', 1, 'MarkerSize', 6)

% Measured results
plot(Meas4plot(1).frame, Meas4plot(1).azi, ...
    'r-', 'LineWidth', 1, 'MarkerSize', 6)
plot(Meas4plot(2).frame, Meas4plot(2).azi, ...
    'rs', 'LineWidth', 1, 'MarkerSize', 6)

% True 
plot(1:Para.N_frame, asind((...
                                    Sys.CarCenter(1:Para.N_frame, 1, 1) ...
                                    - Sys.CarCenter(1:Para.N_frame, 2, 1)) ...
                                    ...
                                    ./...
                                    Distance(...
                                    Sys.CarCenter(1:Para.N_frame, 1, :),...
                                    Sys.CarCenter(1:Para.N_frame, 2, :))), ...
    'g-', 'LineWidth', 2)
plot(1:Para.N_frame, acosd((...
                                    Sys.CarCenter(1:Para.N_frame, 2, 2) ...
                                    - Sys.CarCenter(1:Para.N_frame, 3, 2)) ...
                                    ...
                                    ./...
                                    Distance(...
                                    Sys.CarCenter(1:Para.N_frame, 2, :),...
                                    Sys.CarCenter(1:Para.N_frame, 3, :))), ...
    'g--', 'LineWidth', 2)
ah=axes('position',get(gca,'position'),'visible','off'); 
l2 = legend(ah, [p4, p5],...
    {'True-Vehicle 1', ...
    'True-Vehicle 3'},...
    'Box','off');
l2.FontSize = 14;   
l2.FontName = 'Times New Roman';
%% |    velocity
subplot(3,1,3); set(0,'defaultfigurecolor','w') ;set(gca,'FontName','Times New Roman','FontSize',10);
box on; grid on;
hold on; xlabel('Frame','FontName','Times New Roman','FontSize',14); ylabel('Radial-Velocity [m/s]','FontName','Times New Roman','FontSize',14)
% Fusion results
plot(KF4plot(1).frame, ...
    sqrt(KF4plot(1).mu(3,:).^2 + KF4plot(1).mu(4,:).^2)...
    .*( KF4plot(1).mu(2,:) ...
        ./ sqrt(KF4plot(1).mu(1,:).^2 + KF4plot(1).mu(2,:).^2)) ...
    , ...
    'b-', 'LineWidth', 1, 'MarkerSize', 6)

% Measured results
plot(Meas4plot(1).frame, ...
    (Meas4plot(1).velocity - (Para.N_c/2 + 1))...
            / (Para.N_c*Para.TcAll*Para.fc/3e8), ...
    'r-', 'LineWidth', 1, 'MarkerSize', 6)
plot(Meas4plot(2).frame, ...
    (Meas4plot(2).velocity - (Para.N_c/2 + 1))...
            / (Para.N_c*Para.TcAll*Para.fc/3e8), ...
    'rs', 'LineWidth', 1, 'MarkerSize', 6)

% True 
plot(1:Para.N_frame, ...
    (Para.velocity(2) - Para.velocity(1))*ones(1, Para.N_frame)...
    .*(...
                                    Sys.CarCenter(1:Para.N_frame, 2, 2) ...
                                    - Sys.CarCenter(1:Para.N_frame, 1, 2)) ...
                                    ...
                                    ./...
                                    Distance(...
                                    Sys.CarCenter(1:Para.N_frame, 1, :),...
                                    Sys.CarCenter(1:Para.N_frame, 2, :)), ...
    'g-', 'LineWidth', 2, 'MarkerSize', 6)
plot(1:Para.N_frame, ...
    (Para.velocity(2) - Para.velocity(3))*ones(1, Para.N_frame)...
    .*(...
                                    Sys.CarCenter(1:Para.N_frame, 2, 2) ...
                                    - Sys.CarCenter(1:Para.N_frame, 3, 2)) ...
                                    ...
                                    ./...
                                    Distance(...
                                    Sys.CarCenter(1:Para.N_frame, 2, :),...
                                    Sys.CarCenter(1:Para.N_frame, 3, :)) ...
    + (Para.velocity(3) - Para.velocity(1))*ones(1, Para.N_frame)...
    .*(...
                                    Sys.CarCenter(1:Para.N_frame, 3, 2) ...
                                    - Sys.CarCenter(1:Para.N_frame, 1, 2)) ...
                                    ...
                                    ./...
                                    Distance(...
                                    Sys.CarCenter(1:Para.N_frame, 1, :),...
                                    Sys.CarCenter(1:Para.N_frame, 3, :)), ...
    'g--', 'LineWidth', 2, 'MarkerSize', 6)
%% Performance evaluation of parameters that can only be estimated in state
%% |    orientation, x-velocity and y-velocity
figure; 
 set(gca,'FontName','Times New Roman','FontSize',16);
set(0,'defaultfigurecolor','w');
box on; grid on; hold on;
subplot(1,3,1); 
% Estimated results
Orientation4plot(1).value = atand(KF4plot(1).mu(3,:)./(KF4plot(1).mu(4,:) + Para.velocity(1)));
pp1 = plot(Orientation4plot(1).value, ...
    'r-', 'LineWidth', 1, 'MarkerSize', 6);
xlabel('Frame','Interpreter','latex','FontName','Times New Roman','FontSize',16);
ylabel('Orientation Error [deg]','Interpreter','latex','FontName','Times New Roman','FontSize',16)
set(gca,'FontName','Times New Roman', 'FontSize', 16)



% Fusion results
subplot(1,3,2); 
pp2 = plot(...
    KF4plot(1).mu(3,:), ...
    'r-', 'LineWidth', 1, 'MarkerSize', 6);
xlabel('Frame','Interpreter','latex','FontName','Times New Roman','FontSize',16);
ylabel('$v_x$ Error [m/s]','Interpreter','latex','FontName','Times New Roman','FontSize',16)
ylim([-10, 10])
set(gca,'FontName','Times New Roman', 'FontSize', 16)


subplot(1,3,3); 
pp3 = plot(...
    KF4plot(1).mu(4,:) + Para.velocity(1) - Para.velocity(2)*ones(1, Para.N_frame), ...
    'r-', 'LineWidth', 1, 'MarkerSize', 6);
xlabel('Frame','Interpreter','latex','FontName','Times New Roman','FontSize',16);
ylabel('$v_y$ Error [m/s]','Interpreter','latex','FontName','Times New Roman','FontSize',16)
ylim([-10, 10])
set(gca,'FontName','Times New Roman', 'FontSize', 16)