clear;clc
% close all
addpath('..')
addpath('..\Function\')
load('..\Data\InfoFusion\RT_track_P_5dBm_CovPred_AlwaysLow.mat')
%% Re-organize the fusion resluts
% used to compare with Rectangular coordinate system parameters in system object 'Para'

% extract info of fusion results into array for visualization.
% every KF4plot represents a target.
% every column in KF4plot represents a period.
KF4plot = ...
    struct( ...
    'label',[],...
    'period',[],...
    'mu', [], ...
    'var', []);
for i = 1:Para.N_frame/Para.N_period
    % if KF(i).label doesn't exist in KF4plot, then add it in
    AllLabel_i = char(KF(i).label);
    for j = 1:size(AllLabel_i, 1)
    % j-th target in i-th period of 'KF(i)'
        if isempty([KF4plot.label])
        % if KF4plot is empty, then add the new target info into it unconditionally
            KF4plot(1).label = AllLabel_i(j,:);
            KF4plot(1).period = i;
            KF4plot(1).mu = cell2mat(KF(i).mu(j));
            KF4plot(1).var = reshape(cell2mat(KF(i).var(j)), [], 1);
        else
        %   if KF4plot is not empty, then determine if AllLabel_i(j,:) is in
        % KF4plot.
        %   if yes, determine the index in KF4plot and add the info of
        % 'j-th target in i-th period' in.
        %   if not, add a new struct of KF4plot.
            index = find (...
                        all( repmat(AllLabel_i(j,:), numel(KF4plot), 1)...
                        == char(KF4plot(:).label) , 2)...
                        );            
            if isempty(index)
                KF4plot(numel(KF4plot)+1).label = AllLabel_i(j,:);
                KF4plot(numel(KF4plot)).period = i;
                KF4plot(numel(KF4plot)).mu = cell2mat(KF(i).mu(j));
                KF4plot(numel(KF4plot)).var = reshape(cell2mat(KF(i).var(j)), [], 1);                
            else                
                KF4plot(index).period = [KF4plot(index).period, ...
                                        i];
                KF4plot(index).mu = [KF4plot(index).mu,...
                                    cell2mat(KF(i).mu(j))];
                KF4plot(index).var = [KF4plot(index).var,...
                    reshape(cell2mat(KF(i).var(j)), [], 1)];
            end
        end
        
    end
end
%% Re-organize the measurement results
% used to compare with polar-domain coordinate system parameters of 'ParaAll_A.EachFrameTrue'

% extract info of fusion results into array for visualization.
% every Meas4plot represents a target.
% every column in KF4plot represents a period.
Meas4plot = ...
    struct( ...
    'label',[],...
    'period',[],...
    'range', [], ...
    'velocity', [], ...
    'azi', []);
for i = 1:Para.N_frame/Para.N_period
    %   if 'ParaAll_A.EachPeriodEst(i).TargetList(:).label' doesn't exist in 
    % Meas4plot, then add it in
    AllLabel_i = char(ParaAll_A.EachPeriodEst(i).TargetList(:).label);
    for j = 1:size(AllLabel_i, 1)
    % j-th target in i-th period of 'ParaAll_A.EachPeriodEst'
        if isempty([Meas4plot.label])
        % if KF4plot is empty, then add the new target info into it unconditionally
            Meas4plot(1).label = AllLabel_i(j,:);
            Meas4plot(1).period = i;
            Meas4plot(1).range = ParaAll_A.EachPeriodEst(i).TargetList(j).range_average;
            Meas4plot(1).velocity = ParaAll_A.EachPeriodEst(i).TargetList(j).velocity_average;
            Meas4plot(1).azi = ParaAll_A.EachPeriodEst(i).TargetList(j).azi_average;
        else
        %   if Meas4plot is not empty, then determine if AllLabel_i(j,:) is in
        % Meas4plot.
        %   if yes, determine the index in Meas4plot and add the info of
        % 'j-th target in i-th period' in.
        %   if not, add a new struct of Meas4plot.
            index = find (...
                        all( repmat(AllLabel_i(j,:), numel(Meas4plot), 1)...
                        == char(Meas4plot(:).label) , 2)...
                        );
            if isempty(index)
                Meas4plot(numel(Meas4plot)+1).label = AllLabel_i(j,:);
                Meas4plot(numel(Meas4plot)).period = i;
                Meas4plot(numel(Meas4plot)).range = ParaAll_A.EachPeriodEst(i).TargetList(j).range_average;
                Meas4plot(numel(Meas4plot)).velocity = ParaAll_A.EachPeriodEst(i).TargetList(j).velocity_average;
                Meas4plot(numel(Meas4plot)).azi = ParaAll_A.EachPeriodEst(i).TargetList(j).azi_average;
            else                
                Meas4plot(index).period = [Meas4plot(index).period, ...
                                        i];
                Meas4plot(index).range = [Meas4plot(index).range,...
                                    ParaAll_A.EachPeriodEst(i).TargetList(j).range_average];
                Meas4plot(index).velocity = [Meas4plot(index).velocity,...
                                    ParaAll_A.EachPeriodEst(i).TargetList(j).velocity_average];
                Meas4plot(index).azi = [Meas4plot(index).azi,...
                                    ParaAll_A.EachPeriodEst(i).TargetList(j).azi_average];
            end
        end
        
    end
end
%% Obtain the estimated results of orientation
Orientation4plot = ...
    struct( ...
    'label',[],...
    'period',[],...
    'value', []);
for i = 1:Para.N_frame/Para.N_period
    %   if 'ParaAll_A.EachPeriodEst(i).TargetList(:).label' doesn't exist in 
    % Meas4plot, then add it in
    AllLabel_i = char(ParaAll_A.EachPeriodEst(i).TargetList(:).label);
    for j = 1:size(AllLabel_i, 1)
    % j-th target in i-th period of 'ParaAll_A.EachPeriodEst'
        if isempty([Orientation4plot.label])
        % if KF4plot is empty, then add the new target info into it unconditionally
            Orientation4plot(1).label = AllLabel_i(j,:);
            Orientation4plot(1).period = i;
            Orientation4plot(1).value = ParaAll_A.EachPeriodEst(i).TargetList(j).orientation;
        else
        %   if Meas4plot is not empty, then determine if AllLabel_i(j,:) is in
        % Meas4plot.
        %   if yes, determine the index in Meas4plot and add the info of
        % 'j-th target in i-th period' in.
        %   if not, add a new struct of Meas4plot.
            index = find (...
                        all( repmat(AllLabel_i(j,:), numel(Orientation4plot), 1)...
                        == char(Orientation4plot(:).label) , 2)...
                        );
            if isempty(index)
                Orientation4plot(numel(Orientation4plot)+1).label = AllLabel_i(j,:);
                Orientation4plot(numel(Orientation4plot)).period = i;
                Orientation4plot(numel(Orientation4plot)).value = ParaAll_A.EachPeriodEst(i).TargetList(j).orientation;
            else                
                Orientation4plot(index).period = [Orientation4plot(index).period, ...
                                        i];
                Orientation4plot(index).value = [Orientation4plot(index).value,...
                                    ParaAll_A.EachPeriodEst(i).TargetList(j).orientation];
            end
        end
        
    end    
end
%% Performance evaluation of parameters that can be estimated both in measurement and state
%% |    range
figure; title('Comparison between Fusion Results and Measurements')
subplot(3,1,1); set(0,'defaultfigurecolor','w') ; set(gca,'FontName','Times New Roman','FontSize',10);
box on; grid on;hold on;xlabel('Frame','FontName','Times New Roman','FontSize',14);ylabel('Distance [m]','FontName','Times New Roman','FontSize',14)
% Fusion results
p1 = plot(KF4plot(1).period*Para.N_period, sqrt(KF4plot(1).mu(1,:).^2 + KF4plot(1).mu(2,:).^2), ...
    'bx', 'LineWidth', 1, 'MarkerSize', 6);
p2 = plot(KF4plot(2).period*Para.N_period, sqrt(KF4plot(2).mu(1,:).^2 + KF4plot(2).mu(2,:).^2), ...
    'b+', 'LineWidth', 1, 'MarkerSize', 6) ;

% Measured results
plot(Meas4plot(1).period*Para.N_period, (Meas4plot(1).range-1) ./ (4*Para.fs*Para.TcEff/...
            (3e8 * 2*(Para.Tsen+Para.Tcom))), ...
    'ro', 'LineWidth', 1, 'MarkerSize', 6);
plot(Meas4plot(2).period*Para.N_period, (Meas4plot(2).range-1)./ (4*Para.fs*Para.TcEff/...
            (3e8 * 2*(Para.Tsen+Para.Tcom))), ...
    'rs', 'LineWidth', 1, 'MarkerSize', 6);

% True 
plot(Para.N_period:Para.N_period:Para.N_frame, Distance(...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 1, :),...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 2, :)), ...
    'g-', 'LineWidth', 2, 'MarkerSize', 6);
plot(Para.N_period:Para.N_period:Para.N_frame, Distance(...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 1, :),...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 3, :)), ...
    'g--', 'LineWidth', 2, 'MarkerSize', 6);
ah=axes('position',get(gca,'position'),'visible','off'); 
l1 = legend(ah, [p1, p2], {'Fused-Vehicle 2',...
    'Fused-Vehicle 3'},...
    'Box','off');
l1.FontSize = 14;
l1.FontName = 'Times New Roman';
%% |    azimuth
subplot(3,1,2); set(0,'defaultfigurecolor','w') ;set(gca,'FontName','Times New Roman','FontSize',10);
box on; grid on;hold on; xlabel('Frame','FontName','Times New Roman','FontSize',14);ylabel('Azimuth [deg]','FontName','Times New Roman','FontSize',14)
% Fusion results
plot(KF4plot(1).period*Para.N_period, asind( KF4plot(1).mu(1,:) ...
                                    ./ sqrt(KF4plot(1).mu(1,:).^2 + KF4plot(1).mu(2,:).^2)), ...
    'bx', 'LineWidth', 1, 'MarkerSize', 6)
plot(KF4plot(2).period*Para.N_period, acosd( KF4plot(2).mu(2,:) ...
                                    ./ sqrt(KF4plot(2).mu(1,:).^2 + KF4plot(2).mu(2,:).^2)), ...
    'b+', 'LineWidth', 1, 'MarkerSize', 6)

% Measured results
p3 = plot(Meas4plot(1).period*Para.N_period, Meas4plot(1).azi, ...
    'ro', 'LineWidth', 1, 'MarkerSize', 6);
p4 = plot(Meas4plot(2).period*Para.N_period, Meas4plot(2).azi, ...
    'rs', 'LineWidth', 1, 'MarkerSize', 6);

% True 
p5 = plot(Para.N_period:Para.N_period:Para.N_frame, asind((...
                                    Sys.CarCenter(1:Para.N_period:Para.N_frame, 2, 1) ...
                                    - Sys.CarCenter(1:Para.N_period:Para.N_frame, 1, 1)) ...
                                    ...
                                    ./...
                                    Distance(...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 1, :),...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 2, :))), ...
    'g-', 'LineWidth', 2);
p6 = plot(Para.N_period:Para.N_period:Para.N_frame, acosd((...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 3, 2) ...
                                    - Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 1, 2)) ...
                                    ...
                                    ./...
                                    Distance(...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 1, :),...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 3, :))), ...
    'g--', 'LineWidth', 2);
ah2=axes('position',get(gca,'position'),'visible','off'); 
l2 = legend(ah2, [p5, p6],{'True-Vehicle 2', ...
    'True-Vehicle 3'},...
    'Box','off');
l2.FontSize = 14; 
l2.FontName = 'Times New Roman';
%% |    velocity

subplot(3,1,3); set(0,'defaultfigurecolor','w') ;set(gca,'FontName','Times New Roman','FontSize',10);
box on; grid on;hold on; xlabel('Frame','FontName','Times New Roman','FontSize',14); ylabel('Radial-Velocity [m/s]','FontName','Times New Roman','FontSize',14)
% Fusion results
p1 = plot(KF4plot(1).period*Para.N_period, ...
    sqrt(KF4plot(1).mu(3,:).^2 + KF4plot(1).mu(4,:).^2)...
    .*( KF4plot(1).mu(2,:) ...
        ./ sqrt(KF4plot(1).mu(1,:).^2 + KF4plot(1).mu(2,:).^2)) ...
    , ...
    'bx', 'LineWidth', 1, 'MarkerSize', 6);
p2 = plot(KF4plot(2).period*Para.N_period, ...
    sqrt(KF4plot(2).mu(3,:).^2 + KF4plot(2).mu(4,:).^2)...
    .* (KF4plot(2).mu(2,:) ...
       ./ sqrt(KF4plot(2).mu(1,:).^2 + KF4plot(2).mu(2,:).^2)), ...
    'b+', 'LineWidth', 1, 'MarkerSize', 6);

% Measured results
p3 = plot(Meas4plot(1).period*Para.N_period, ...
    (Meas4plot(1).velocity - (Para.N_c/2 + 1))...
            / (2*Para.N_c*Para.TcAll*Para.fc/3e8), ...
    'ro', 'LineWidth', 1, 'MarkerSize', 6);
p4 = plot(Meas4plot(2).period*Para.N_period, ...
    (Meas4plot(2).velocity - (Para.N_c/2 + 1))...
            / (2*Para.N_c*Para.TcAll*Para.fc/3e8), ...
    'rs', 'LineWidth', 1, 'MarkerSize', 6);

p5 = plot(Para.N_period:Para.N_period:Para.N_frame, ...
    (Para.velocity(2) - Para.velocity(1))*ones(1, Para.N_frame/Para.N_period)...
    .*(...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 2, 2) ...
                                    - Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 1, 2)) ...
                                    ...
                                    ./...
                                    Distance(...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 1, :),...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 2, :)), ...
    'g-', 'LineWidth', 2);
p6 = plot(Para.N_period:Para.N_period:Para.N_frame, ...
    (Para.velocity(3) - Para.velocity(1))*ones(1, Para.N_frame/Para.N_period)...
    .*(...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 3, 2) ...
                                    - Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 1, 2)) ...
                                    ...
                                    ./...
                                    Distance(...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 1, :),...
                                    Sys.CarCenter(Para.N_period:Para.N_period:Para.N_frame, 3, :)), ...
    'g--', 'LineWidth', 2);
ah3=axes('position',get(gca,'position'),'visible','off'); 
l3 = legend(ah3, [p3, p4], ...
    {'Measured-Vehicle 2', ...
    'Measured-Vehicle 3'},...
    'Box','off');
l3.FontSize = 14; 
l3.FontName = 'Times New Roman';
%% Performance evaluation of parameters that can only be estimated in state
%% |    orientation, x-velocity and y-velocity
figure; 
 set(gca,'FontName','Times New Roman','FontSize',16);
set(0,'defaultfigurecolor','w');
box on; grid on; hold on;
subplot(1,3,1); 
% Estimated results
Orientation4plot(1).value = atand(KF4plot(1).mu(3,:)./(KF4plot(1).mu(4,:) + Para.velocity(1)));
pp1 = plot(Orientation4plot(1).period*Para.N_period, Orientation4plot(1).value, ...
    'r-', 'LineWidth', 1, 'MarkerSize', 6);
xlabel('Frame','Interpreter','latex','FontName','Times New Roman','FontSize',16);
ylabel('Orientation Error [deg]','Interpreter','latex','FontName','Times New Roman','FontSize',16)
set(gca,'FontName','Times New Roman', 'FontSize', 16)



% Fusion results
subplot(1,3,2); 
 
pp2 = plot(KF4plot(1).period*Para.N_period, ...
    KF4plot(1).mu(3,:), ...
    'r-', 'LineWidth', 1, 'MarkerSize', 6);
xlabel('Frame','Interpreter','latex','FontName','Times New Roman','FontSize',16);
ylabel('$v_x$ Error [m/s]','Interpreter','latex','FontName','Times New Roman','FontSize',16)
ylim([-10, 10])
set(gca,'FontName','Times New Roman', 'FontSize', 16)


subplot(1,3,3); 
pp3 = plot(KF4plot(1).period*Para.N_period, ...
    KF4plot(1).mu(4,:) + Para.velocity(1) - Para.velocity(2)*ones(1, Para.N_frame/Para.N_period), ...
    'r-', 'LineWidth', 1, 'MarkerSize', 6);
xlabel('Frame','Interpreter','latex','FontName','Times New Roman','FontSize',16);
ylabel('$v_y$ Error [m/s]','Interpreter','latex','FontName','Times New Roman','FontSize',16)
ylim([-10, 10])
set(gca,'FontName','Times New Roman', 'FontSize', 16)