#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  1 2026

@author: jack

Monte-Carlo simulation of the complete CP-OFDM and Nyquist transmission link:
symbols -> IFFT -> add CP -> manual upsampling -> transmit pulse shaping
-> known frequency-selective Rayleigh channel -> AWGN -> matched filter
-> manual downsampling -> remove CP -> FFT -> known-channel ZF equalization
-> demodulation -> SER
"""

import numpy as np
import scipy
import matplotlib.pyplot as plt

from tqdm import tqdm
from DigiCommPy.modem import PSKModem, QAMModem, PAMModem, FSKModem
from DigiCommPy.errorRates import ser_rayleigh


# 全局设置字体大小
plt.rcParams["font.family"] = "Times New Roman"
plt.rcParams['font.size'] = 14
plt.rcParams['axes.titlesize'] = 16
plt.rcParams['axes.labelsize'] = 16
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams["figure.figsize"] = [8,6]
plt.rcParams['lines.linewidth'] = 2
plt.rcParams['lines.markersize'] = 8
plt.rcParams['figure.facecolor'] = 'white'
plt.rcParams['axes.edgecolor'] = 'black'
plt.rcParams['legend.fontsize'] = 12


# 实现与MATLAB cconv完全一致的圆卷积
def cconv(a, b, n=None):
    a = np.asarray(a,dtype=complex)
    b = np.asarray(b,dtype=complex)
    if n is None:
        n = len(a)+len(b)-1
    linear_conv = np.convolve(a,b,mode='full')
    if n <= 0:
        return np.array([],dtype=complex)
    result = np.zeros(n,dtype=complex)
    if n <= len(linear_conv):
        for k in range(n):
            idx = np.arange(k,len(linear_conv),n)
            result[k] = np.sum(linear_conv[idx])
    else:
        result[:len(linear_conv)] = linear_conv
    return result


def add_cyclic_prefix(x, Ncp):
    x_cp = np.hstack((x[-Ncp:],x))
    return x_cp


def remove_cyclic_prefix(r, Ncp, N):
    y = r[Ncp:Ncp+N]
    return y


# Program 7.8: Square-root raised-cosine pulse characteristics
def srrcFunction(beta, Q, span):
    Tsym = 1
    t = np.arange(-span/2,span/2+0.5/Q,1/Q)
    with np.errstate(divide='ignore',invalid='ignore'):
        A = np.sin(np.pi*t*(1-beta)/Tsym)+4*beta*t/Tsym*np.cos(np.pi*t*(1+beta)/Tsym)
        B = np.pi*t/Tsym*(1-(4*beta*t/Tsym)**2)
        p = A/(np.sqrt(Tsym)*B)
    p[np.isnan(p)] = (1+beta*(4/np.pi-1))/np.sqrt(Tsym)
    p[np.isinf(p)] = beta/np.sqrt(2*Tsym)*((1+2/np.pi)*np.sin(np.pi/(4*beta))+(1-2/np.pi)*np.cos(np.pi/(4*beta)))
    filtDelay = (len(p)-1)/2
    p = p/np.sqrt(np.sum(np.abs(p)**2))
    return p,t,filtDelay


np.random.seed(42)

#---------Input Fields------------------------
nSym = 2000
EbN0dBs = np.arange(start=-4,stop=25,step=4)
MOD_TYPE = "psk"    ## "pam" "psk",   "fsk" is not suitable.
arrayOfOrder = [2,  8, 32]

MOD_TYPE = "qam"
arrayOfOrder = [4, 16, 64,]

coherence = 'coherent'

# OFDM and pulse-shaping parameters
N = 128
Q = 4
beta = 0.3
span = 4
L = 5

# Generate the transmit SRRC pulse and its receive matched filter
p_t,t,filtDelay = srrcFunction(beta,Q,span)
p_r = np.conj(p_t[::-1])
Lp = p_t.size
Lr = p_r.size

# c=p_r*h*p_t has a length fixed by Lp, L and Lr
Lc = Lp+L+Lr-2
n0 = 0
Leq = int(np.floor((Lc-1-n0)/Q)+1)
Ncp = Leq-1
M = N+Ncp

if Ncp > N:
    raise ValueError('Ncp must not exceed N. Increase N or shorten the pulse/channel memory.')

print(f'N = {N}, Q = {Q}, L = {L}, Lp = {Lp}, Lr = {Lr}')
print(f'Lc = {Lc}, n0 = {n0}, Leq = {Leq}, Ncp = {Ncp}, M = {M}')

# Construct the symbol-rate equivalent channel generated by every unit physical tap.
# hEqBasis[:,l] is the equivalent channel h_eq when the physical channel is delta[n-l].
hEqBasis = np.zeros((Leq,L),dtype=complex)
for indexTap in range(L):
    hBasis = np.zeros(L,dtype=complex)
    hBasis[indexTap] = 1
    cBasis = np.convolve(np.convolve(p_t,hBasis),p_r)
    hEqBasis[:,indexTap] = cBasis[n0::Q]

# Use one deterministic normalization for the Rayleigh ensemble; never normalize h realization by realization.
channelNormalization = np.sum(np.abs(hEqBasis)**2)
HEqBasis = scipy.fft.fft(hEqBasis,N,axis=0)
channelPowerSubcarrier = np.sum(np.abs(HEqBasis)**2,axis=1)/channelNormalization
print(f'Equivalent-channel ensemble normalization = {channelNormalization:.6f}')
print(f'Average subcarrier channel power = {np.mean(channelPowerSubcarrier):.6f}')

modem_dict = {'psk':PSKModem,'qam':QAMModem,'pam':PAMModem,'fsk':FSKModem}
colors = plt.cm.jet(np.linspace(0,1,len(arrayOfOrder)))
fig,axs = plt.subplots(1,1,figsize=(8,6),constrained_layout=True)

for indexOrder,Order in enumerate(arrayOfOrder):
    print(f'Order {Order}: {indexOrder+1}/{len(arrayOfOrder)}')
    bitsPerSymbol = int(np.log2(Order))
    errors = np.zeros(EbN0dBs.size)

    if MOD_TYPE.lower() == 'fsk':
        modem = modem_dict[MOD_TYPE.lower()](Order,coherence)
    else:
        modem = modem_dict[MOD_TYPE.lower()](Order)

    AvgEnergy = np.mean(np.abs(modem.constellation)**2)
    EsN0dBs = 10*np.log10(bitsPerSymbol*N/M)+EbN0dBs

    for indexSNR,EbN0dB in enumerate(EbN0dBs):
        print(f'    Eb/N0 = {EbN0dB} dB: {indexSNR+1}/{EbN0dBs.size}')
        EsN0dB = EsN0dBs[indexSNR]
        EsN0 = 10**(EsN0dB/10)

        for indexBlock in tqdm(range(nSym),leave=False):
            # Generate random constellation symbols
            d = np.random.randint(low=0,high=Order,size=N)
            X = modem.modulate(d)

            # OFDM modulation and CP insertion
            x = scipy.fft.ifft(X,N)
            x_cp = add_cyclic_prefix(x,Ncp)

            # Manual Q-fold upsampling
            x_up = np.zeros(Q*M,dtype=complex)
            x_up[0::Q] = x_cp

            # Physical transmit pulse shaping by linear convolution
            x_t = np.convolve(x_up,p_t,mode='full')

            # Known complex frequency-selective Rayleigh channel with deterministic ensemble normalization
            h = (np.random.randn(L)+1j*np.random.randn(L))/np.sqrt(2*channelNormalization)
            c = np.convolve(np.convolve(p_t,h),p_r)
            h_eq = c[n0::Q]

            # Physical linear convolution through the random multipath channel
            r_noiseless = np.convolve(x_t,h,mode='full')

            # Add one high-rate AWGN sequence. After the unit-energy matched filter and N-point FFT,
            # its subcarrier variance is N*noiseVarianceHighRate = AvgEnergy/EsN0.
            noiseVarianceHighRate = AvgEnergy/(N*EsN0)
            noise = np.sqrt(noiseVarianceHighRate/2)*(np.random.randn(r_noiseless.size)+1j*np.random.randn(r_noiseless.size))
            r = r_noiseless+noise

            # Communication receive matched filter by linear convolution
            z = np.convolve(r,p_r,mode='full')

            # Manual Q-fold downsampling from n0
            outputLength = M+Leq-1
            r_d = z[n0:n0+Q*outputLength:Q]

            # Remove the symbol-rate CP
            y = remove_cyclic_prefix(r_d,Ncp,N)

            # FFT and ideal one-tap frequency-domain equalization
            Y = scipy.fft.fft(y,N)
            H_eq = scipy.fft.fft(h_eq,N)
            X_hat = Y/H_eq

            # Verify the noiseless complete-link identities in the first block
            if indexOrder == 0 and indexSNR == 0 and indexBlock == 0:
                z_noiseless = np.convolve(r_noiseless,p_r,mode='full')
                r_d_noiseless = z_noiseless[n0:n0+Q*outputLength:Q]
                y_noiseless = remove_cyclic_prefix(r_d_noiseless,Ncp,N)
                y_circular = cconv(h_eq,x,N)
                X_noiseless_hat = scipy.fft.fft(y_noiseless,N)/H_eq
                equivalentChannelError = np.linalg.norm(r_d_noiseless-np.convolve(x_cp,h_eq,mode='full'))
                circularizationError = np.linalg.norm(y_noiseless-y_circular)
                noiselessRecoveryError = np.linalg.norm(X_noiseless_hat-X)
                print(f'\n    Equivalent channel error = {equivalentChannelError:.3e}')
                print(f'    CP circularization error = {circularizationError:.3e}')
                print(f'    Noiseless recovery error = {noiselessRecoveryError:.3e}\n')

            # Constellation demodulation
            if MOD_TYPE.lower() == 'fsk':
                dCap = modem.demodulate(X_hat,coherence)
            else:
                dCap = modem.demodulate(X_hat)

            numErrors = np.sum(d != dCap)
            errors[indexSNR] += numErrors

    SER_sim = errors/(nSym*N)
    EbN0EffectiveDbs = EbN0dBs+10*np.log10(N/M)
    SER_theory = np.zeros(EbN0dBs.size)
    for indexSubcarrier in range(N):
        EbN0SubcarrierDbs = EbN0EffectiveDbs+10*np.log10(channelPowerSubcarrier[indexSubcarrier])
        SER_theory += ser_rayleigh(EbN0SubcarrierDbs,MOD_TYPE,Order)
    SER_theory = SER_theory/N
    axs.semilogy(EbN0dBs,SER_sim,color=colors[indexOrder],marker='o',linestyle='none',label=f'{Order}-{MOD_TYPE.upper()}, Simulation')
    axs.semilogy(EbN0dBs,SER_theory,color=colors[indexOrder],linestyle='-',label=f'{Order}-{MOD_TYPE.upper()}, Theoretical')

axs.set_ylim([1e-4,1])
axs.set_xlabel('Eb/N0 (dB)')
axs.set_ylabel('SER ($P_s$)')
axs.set_title('CP-OFDM With Nyquist Pulse Shaping Over Frequency-Selective Rayleigh Channel')
axs.grid(True,which='both',linestyle='--',alpha=0.3)
axs.legend(loc='best',edgecolor='black')

# plt.savefig('CP_OFDM_Nyquist_Full_Link_SER.pdf',bbox_inches='tight')
# plt.savefig('CP_OFDM_Nyquist_Full_Link_SER.png',dpi=300,bbox_inches='tight')
plt.show()
plt.close()
